/// AG-5 test-mirroring checker — AUD-app-05.
///
/// AG-5 (docs/coding-standards.md): `test/` mirrors `lib/` 1:1 —
/// `lib/a/b/foo.dart` must have a test at `test/a/b/foo_test.dart`.
/// `test/story_acceptance/**` is exempt (those are cross-cutting acceptance
/// suites, not per-file unit mirrors).
///
/// This checker is a RATCHET, not a full-repo hard-fail: the existing
/// backlog (hundreds of pre-existing unmirrored files) is tracked in
/// [_baselinePath] and tolerated. The gate only fails when a NEW unmirrored
/// file appears that is not already in the baseline — i.e. it prevents the
/// backlog from growing while a burn-down happens incrementally, finding by
/// finding. Directories that have been fully burned down (e.g.
/// `lib/core/sync/merge/`, `lib/core/sync/codec/` — AUD-app-05) will fail
/// immediately if a fresh unmirrored file appears there, because the
/// baseline no longer carries any entries for them.
///
/// Usage:
///   dart run tool/check_test_mirroring.dart            # ratchet check
///   dart run tool/check_test_mirroring.dart --report    # print full list, exit 0
///   dart run tool/check_test_mirroring.dart --update-baseline
///
/// Exit codes (ratchet mode):
///   0 — no unmirrored file outside the tracked baseline
///   1 — one or more NEW unmirrored files found (prints them)
library;

import 'dart:io';

/// Baseline of already-known unmirrored files (the pre-existing backlog).
/// Maintainers burn this down by moving/adding mirrored tests and re-running
/// with `--update-baseline`; the ratchet then locks the new, smaller count.
const _baselinePath = 'tool/ag5_unmirrored_baseline.txt';

/// Generated/entrypoint files that AG-5 does not apply to.
bool _isExempt(String libRelativePath) {
  if (libRelativePath.endsWith('.g.dart')) return true;
  if (libRelativePath.endsWith('.freezed.dart')) return true;
  if (libRelativePath.endsWith('.gr.dart')) return true; // auto_route codegen
  if (libRelativePath == 'lib/main.dart') return true;
  if (libRelativePath == 'lib/firebase_options.dart') return true;
  return false;
}

/// Maps a `lib/...` path to its expected AG-5-mirrored test path.
String _expectedTestPath(String libRelativePath) {
  // lib/a/b/foo.dart -> test/a/b/foo_test.dart
  final withoutLib = libRelativePath.substring('lib/'.length);
  final dotIndex = withoutLib.lastIndexOf('.dart');
  final withoutExt = withoutLib.substring(0, dotIndex);
  return 'test/$withoutExt'
      '_test.dart';
}

List<String> _findUnmirrored() {
  final libDir = Directory('lib');
  if (!libDir.existsSync()) {
    stderr.writeln(
      'ERROR: lib/ not found — run from the learning_tracker/ directory',
    );
    exit(2);
  }

  final unmirrored = <String>[];
  for (final entity in libDir.listSync(recursive: true)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.dart')) continue;
    // Normalise to forward-slash relative path regardless of platform.
    final libPath = entity.path.replaceAll(r'\', '/');
    if (_isExempt(libPath)) continue;

    final expected = _expectedTestPath(libPath);
    if (!File(expected).existsSync()) {
      unmirrored.add(libPath);
    }
  }
  unmirrored.sort();
  return unmirrored;
}

Set<String> _readBaseline() {
  final file = File(_baselinePath);
  if (!file.existsSync()) return <String>{};
  return file
      .readAsLinesSync()
      .map((l) => l.trim())
      .where((l) => l.isNotEmpty && !l.startsWith('#'))
      .toSet();
}

void _writeBaseline(List<String> entries) {
  final buffer = StringBuffer()
    ..writeln('# AG-5 unmirrored-test baseline — generated by')
    ..writeln('# tool/check_test_mirroring.dart --update-baseline.')
    ..writeln(
      '# Pre-existing backlog only. A new unmirrored file NOT listed here',
    )
    ..writeln('# fails `make audit`. Burn this list down over time — do NOT')
    ..writeln('# add fresh entries to paper over a new violation.');
  for (final entry in entries) {
    buffer.writeln(entry);
  }
  File(_baselinePath).writeAsStringSync(buffer.toString());
}

void main(List<String> args) {
  final report = args.contains('--report');
  final updateBaseline = args.contains('--update-baseline');
  final unmirrored = _findUnmirrored();

  if (updateBaseline) {
    _writeBaseline(unmirrored);
    stdout.writeln(
      'Baseline updated: ${unmirrored.length} unmirrored file(s) recorded '
      'in $_baselinePath',
    );
    return;
  }

  if (report) {
    for (final path in unmirrored) {
      stdout.writeln(path);
    }
    stdout.writeln('--- ${unmirrored.length} unmirrored lib/ file(s) total');
    return;
  }

  final baseline = _readBaseline();
  final unmirroredSet = unmirrored.toSet();
  final newViolations = unmirroredSet.difference(baseline).toList()..sort();

  if (newViolations.isNotEmpty) {
    stderr.writeln(
      'AG-5 (test/ mirrors lib/ 1:1) — NEW unmirrored file(s) not in the '
      'tracked baseline ($_baselinePath):',
    );
    for (final path in newViolations) {
      final expected = _expectedTestPath(path);
      stderr.writeln('  $path -> missing $expected');
    }
    stderr.writeln(
      '\nAdd a mirrored test at the path(s) above, OR if this is a '
      'deliberate, reviewed addition to the tracked backlog, regenerate the '
      'baseline with `dart run tool/check_test_mirroring.dart '
      '--update-baseline` (only after team sign-off — this widens the '
      'ratchet).',
    );
    exit(1);
  }

  stdout.writeln(
    'AG-5 ratchet OK: ${unmirroredSet.length} unmirrored file(s), all '
    'within the tracked baseline (0 new violations).',
  );
}
