/// `dart_test.yaml` tag-registry checker/generator — AUD-guardrails-34.
///
/// `dart_test.yaml`'s `tags:` block exists to suppress `package:test`'s
/// "unknown tag" warning when running `flutter test --tags <tag>` (see the
/// file's own header comment). AUD-guardrails-34 found the hand-maintained
/// registry had drifted so far from actual usage that most tags used via
/// `@Tags([...])`/`tags: [...]` across `test/` were undeclared — including
/// entire epics with their own Makefile targets (epic_18, epic_20, epic_24,
/// epic_28) — defeating the file's one stated job and adding warning noise
/// that makes genuine problems easy to miss in CI logs.
///
/// This script scans every `test/**/*.dart` file for tag string literals
/// passed to `@Tags([...])` or a `tags: [...]` group()/test() parameter, and
/// treats that as the source of truth — `dart_test.yaml`'s declared set must
/// be a superset (in practice, exactly equal after `--write`).
///
/// Usage (from `learning_tracker/`):
///   dart run tool/check_dart_test_tags.dart              # print the regenerated tags: block
///   dart run tool/check_dart_test_tags.dart --check       # exit 1 if any tag used under
///                                                          # test/ is undeclared in
///                                                          # dart_test.yaml (the `comm -23`
///                                                          # check from AUD-guardrails-34's
///                                                          # acceptance criterion)
///   dart run tool/check_dart_test_tags.dart --write       # regenerate dart_test.yaml in
///                                                          # place from the scan
///
/// Exit codes (`--check` mode):
///   0 — every tag used under test/ is declared in dart_test.yaml
///   1 — one or more used tags are undeclared (prints the missing set)
library;

import 'dart:io';

/// Matches an `@Tags([...])` annotation, capturing the bracket body. Uses a
/// negated character class (not `.`) so it spans multi-line tag lists too —
/// e.g. `@Tags([\n  'tracks',\n  'edit_track',\n])`.
final _atTagsPattern = RegExp(r'@Tags\(\[([^\]]*)\]\)');

/// Matches a `tags: [...]` group()/test() parameter, same multi-line
/// handling as [_atTagsPattern].
final _tagsKeywordPattern = RegExp(r'tags:\s*\[([^\]]*)\]');

/// A single quoted string literal inside a tag-list bracket body.
final _stringLiteralPattern = RegExp('''['"]([^'"]+)['"]''');

/// A bare `  <tag>:` entry under dart_test.yaml's top-level `tags:` map —
/// this repo's registry never assigns a value (no `skip:`/`timeout:` per
/// tag), so every declared tag is a colon-terminated key on its own line.
final _declaredTagPattern = RegExp(
  r'^  ([a-zA-Z0-9_-]+):\s*$',
  multiLine: true,
);

/// Scans [testDir] recursively for every tag literal used via `@Tags([...])`
/// or `tags: [...]`.
Set<String> scanUsedTags(Directory testDir) {
  final used = <String>{};
  for (final entity in testDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final content = entity.readAsStringSync();
    for (final pattern in [_atTagsPattern, _tagsKeywordPattern]) {
      for (final match in pattern.allMatches(content)) {
        final body = match.group(1)!;
        for (final lit in _stringLiteralPattern.allMatches(body)) {
          used.add(lit.group(1)!);
        }
      }
    }
  }
  return used;
}

/// Parses the tag keys currently declared in dart_test.yaml's `tags:` block.
Set<String> declaredTags(String yamlContent) {
  return _declaredTagPattern
      .allMatches(yamlContent)
      .map((m) => m.group(1)!)
      .toSet();
}

/// Builds the full replacement contents of dart_test.yaml from a scanned tag
/// set — a flat, alphabetically-sorted registry (the previous hand-grouped
/// per-epic comments could not be kept accurate across waves; the checker
/// itself is now the source of truth — see the `--write` usage note below).
String buildDartTestYaml(Set<String> tags) {
  final sorted = tags.toList()..sort();
  final buffer = StringBuffer()
    ..writeln('# Tag registration for story acceptance tests.')
    ..writeln(
      '# Prevents "unknown tag" warnings when running flutter test --tags.',
    )
    ..writeln('#')
    ..writeln(
      '# GENERATED by tool/check_dart_test_tags.dart --write (AUD-guardrails-34).',
    )
    ..writeln(
      '# Do not hand-edit: run `dart run tool/check_dart_test_tags.dart --write`',
    )
    ..writeln(
      '# after adding/removing an @Tags([...])/tags: [...] literal under test/, and',
    )
    ..writeln(
      '# commit the result. `dart run tool/check_dart_test_tags.dart --check` (part',
    )
    ..writeln(
      '# of `make audit`) fails if this file drifts from actual usage again.',
    )
    ..writeln()
    ..writeln('tags:');
  for (final tag in sorted) {
    buffer.writeln('  $tag:');
  }
  return buffer.toString();
}

void main(List<String> args) {
  final testDir = Directory('test');
  if (!testDir.existsSync()) {
    stderr.writeln('ERROR: test/ not found — run from learning_tracker/');
    exit(2);
  }
  final yamlFile = File('dart_test.yaml');
  if (!yamlFile.existsSync()) {
    stderr.writeln(
      'ERROR: dart_test.yaml not found — run from learning_tracker/',
    );
    exit(2);
  }

  final used = scanUsedTags(testDir);
  final check = args.contains('--check');
  final write = args.contains('--write');

  if (check) {
    final declared = declaredTags(yamlFile.readAsStringSync());
    final missing = used.difference(declared).toList()..sort();
    if (missing.isNotEmpty) {
      stderr.writeln(
        'AUD-guardrails-34 dart_test.yaml tag check FAILED: ${missing.length} '
        'tag(s) used under test/ via @Tags([...])/tags: [...] are not '
        "declared in dart_test.yaml's tags: block:",
      );
      for (final tag in missing) {
        stderr.writeln('  $tag');
      }
      stderr.writeln(
        '\nRun `dart run tool/check_dart_test_tags.dart --write` to '
        'regenerate the tags: block, then commit the result.',
      );
      exit(1);
    }
    stdout.writeln(
      'dart_test.yaml tag check OK: all ${used.length} tag(s) used under '
      'test/ are declared.',
    );
    return;
  }

  final regenerated = buildDartTestYaml(used);
  if (write) {
    yamlFile.writeAsStringSync(regenerated);
    stdout.writeln(
      'dart_test.yaml regenerated with ${used.length} declared tag(s).',
    );
    return;
  }

  stdout.write(regenerated);
}
