/// AUD-t-profiles-02 Rule-0 checker — TQ-3 `pumpApp` migration ratchet.
///
/// TQ-3 (docs/coding-standards.md) calls for widget tests to pump through a
/// shared `pumpApp` helper (`test/helpers/pump_app.dart`) instead of
/// hand-rolling the `MaterialApp(localizationsDelegates: [...])` boilerplate
/// at every call site. AUD-t-profiles-02 found the profiles feature alone
/// hand-rolled that identical 4-delegate block 13 times across 4 files, and
/// a repo-wide grep for `GlobalCupertinoLocalizations.delegate` outside
/// `test/helpers/` found 283 occurrences across 160 files before the fix.
///
/// This checker is a RATCHET, not a full-repo hard-fail — the pre-existing
/// backlog (hundreds of not-yet-migrated call sites) is tracked as a
/// baseline COUNT in [_baselinePath], the same shape as AG-5's
/// `check_test_mirroring.dart` (a tracked baseline, gate fails only on
/// growth). AUD-t-profiles-02's own fix migrated 4 files
/// (`an2_switcher_pin_guard_test.dart`, `pin_flow_and_setup_dialog_l1_test
/// .dart`, `profile_switcher_sheet_test.dart`,
/// `manage_learners_screen_l1_test.dart`) onto `pumpApp`, dropping the
/// occurrence count from 283 to 269 — the baseline below reflects that new,
/// lower count. A future PR that hand-rolls a NEW
/// `MaterialApp(localizationsDelegates: [...])` block (raising the count
/// above the baseline) fails this gate; a PR that migrates more call sites
/// onto `pumpApp` (lowering the count) re-runs with `--update-baseline` to
/// lock the win in, burning the backlog down over time.
///
/// Usage:
///   dart run tool/check_tq3_pump_app_migration.dart            # ratchet check
///   dart run tool/check_tq3_pump_app_migration.dart --update-baseline
///
/// Exit codes (ratchet mode):
///   0 — occurrence count is at or below the tracked baseline
///   1 — occurrence count exceeds the tracked baseline (prints the delta)
library;

import 'dart:io';

/// Baseline occurrence count (the pre-existing, not-yet-migrated backlog).
/// Maintainers burn this down by migrating more call sites onto `pumpApp`
/// and re-running with `--update-baseline`; the ratchet then locks the new,
/// smaller count.
const _baselinePath = 'tool/tq3_pump_app_delegate_baseline.txt';

/// The literal that marks a hand-rolled (non-`pumpApp`) localization-delegate
/// list — every hand-rolled block in this codebase includes this delegate,
/// so counting it is a reliable proxy for counting hand-rolled blocks.
const _needle = 'GlobalCupertinoLocalizations.delegate';

int _countOutsideHelpers() {
  final testDir = Directory('test');
  if (!testDir.existsSync()) {
    stderr.writeln('ERROR: test/ not found — run from learning_tracker/.');
    exit(1);
  }
  var count = 0;
  for (final entity in testDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final normalized = entity.path.replaceAll(r'\', '/');
    if (normalized.startsWith('test/helpers/')) continue;
    final content = entity.readAsStringSync();
    count += _needle.allMatches(content).length;
  }
  return count;
}

int _readBaseline() {
  final file = File(_baselinePath);
  if (!file.existsSync()) return 0;
  final dataLine = file.readAsLinesSync().firstWhere(
    (l) => l.trim().isNotEmpty && !l.trim().startsWith('#'),
    orElse: () => '0',
  );
  return int.tryParse(dataLine.trim()) ?? 0;
}

void main(List<String> args) {
  final actual = _countOutsideHelpers();

  if (args.contains('--update-baseline')) {
    File(_baselinePath).writeAsStringSync(
      '# TQ-3 pumpApp migration ratchet baseline — generated by\n'
      '# tool/check_tq3_pump_app_migration.dart --update-baseline.\n'
      '# Tracks the count of "$_needle" occurrences under test/ but outside\n'
      '# test/helpers/ — i.e. call sites NOT yet migrated onto\n'
      '# test/helpers/pump_app.dart\'s pumpApp() helper (AUD-t-profiles-02).\n'
      '# Lower this only by migrating more call sites onto pumpApp — do NOT\n'
      '# raise it to paper over a new hand-rolled MaterialApp delegate block.\n'
      '$actual\n',
    );
    stdout.writeln('Baseline updated to $actual.');
    return;
  }

  final baseline = _readBaseline();
  if (actual > baseline) {
    stderr.writeln(
      'TQ-3 pumpApp migration ratchet FAILED (AUD-t-profiles-02) — '
      '"$_needle" occurs $actual time(s) under test/ outside test/helpers/, '
      'up from the tracked baseline of $baseline. A widget test hand-rolled '
      'a new MaterialApp(localizationsDelegates: [...]) block instead of '
      'using test/helpers/pump_app.dart\'s pumpApp() helper. Migrate the new '
      'call site onto pumpApp(); if you deliberately migrated MORE call '
      'sites and lowered the count instead, re-run with --update-baseline '
      'to lock the win in.',
    );
    exit(1);
  }

  stdout.writeln(
    'TQ-3 pumpApp migration ratchet passed — $actual occurrence(s) of '
    '"$_needle" under test/ outside test/helpers/ (tracked baseline: '
    '$baseline).',
  );
}
