/// AUD-scheduler-23 Rule-0 checker — SM-7 `LearningProgramRepository.instance`
/// singleton ratchet.
///
/// SM-7 (`docs/coding-standards.md`) bans global/static mutable singletons —
/// repositories are to be constructed only inside their `@riverpod` provider
/// or a test override. `LearningProgramRepository.instance`
/// (`lib/features/scheduler/domain/services/learning_program_service.dart`)
/// is `@Deprecated('Use learningProgramRepositoryProvider via Riverpod
/// instead')` and has zero production (`lib/`) call sites, but AUD-scheduler-23
/// found 11 test files / 34 call sites across the suite still constructing
/// fixtures via the singleton instead of overriding
/// `learningProgramRepositoryProvider`. Because `test/` and `lib/` share one
/// Dart package, the default `deprecated_member_use` lint never fires for
/// same-package usage (only `deprecated_member_use_from_same_package` would,
/// and it isn't enabled), so `flutter analyze` stays green while this
/// backlog exists — nothing else in the toolchain catches it.
///
/// This checker is a RATCHET, not a full-repo hard-fail — the same shape as
/// `tool/check_tq3_pump_app_migration.dart` (AUD-t-profiles-02): the
/// pre-existing 34 call sites are tracked as a baseline COUNT in
/// [_baselinePath] (backlog paydown tracked at DNI-446), so the gate fails
/// only on a NEW call site pushing the count above the baseline — matching
/// AUD-scheduler-23's acceptance criterion "new test code does not introduce
/// further LearningProgramRepository.instance call sites". Migrate a call
/// site onto a `learningProgramRepositoryProvider` override, then re-run
/// with `--update-baseline` to lock the win in and burn the backlog down;
/// once the count reaches 0, delete the singleton itself (see DNI-446).
///
/// Usage:
///   dart run tool/check_sm7_learning_program_singleton.dart            # ratchet check
///   dart run tool/check_sm7_learning_program_singleton.dart --update-baseline
///
/// Exit codes (ratchet mode):
///   0 — occurrence count is at or below the tracked baseline
///   1 — occurrence count exceeds the tracked baseline (prints the delta)
library;

import 'dart:io';

/// Baseline occurrence count (the pre-existing, not-yet-migrated backlog,
/// tracked at DNI-446). Maintainers burn this down by migrating call sites
/// onto a `learningProgramRepositoryProvider` override and re-running with
/// `--update-baseline`; the ratchet then locks the new, smaller count.
const _baselinePath = 'tool/sm7_learning_program_singleton_baseline.txt';

/// The literal that marks a direct singleton read.
const _needle = 'LearningProgramRepository.instance';

int _countInTests() {
  final testDir = Directory('test');
  if (!testDir.existsSync()) {
    stderr.writeln('ERROR: test/ not found — run from learning_tracker/.');
    exit(1);
  }
  var count = 0;
  for (final entity in testDir.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    final content = entity.readAsStringSync();
    count += _needle.allMatches(content).length;
  }
  return count;
}

int _readBaseline() {
  final file = File(_baselinePath);
  if (!file.existsSync()) return 0;
  final dataLine = file.readAsLinesSync().firstWhere(
    (l) => l.trim().isNotEmpty && !l.trim().startsWith('#'),
    orElse: () => '0',
  );
  return int.tryParse(dataLine.trim()) ?? 0;
}

void main(List<String> args) {
  final actual = _countInTests();

  if (args.contains('--update-baseline')) {
    File(_baselinePath).writeAsStringSync(
      '# SM-7 LearningProgramRepository.instance singleton ratchet baseline\n'
      '# — generated by tool/check_sm7_learning_program_singleton.dart\n'
      '# --update-baseline. Tracks the count of "$_needle" occurrences under\n'
      '# test/ — i.e. call sites NOT yet migrated onto a\n'
      '# learningProgramRepositoryProvider override (AUD-scheduler-23,\n'
      '# backlog paydown tracked at DNI-446).\n'
      '# Lower this only by migrating more call sites off the singleton — do\n'
      '# NOT raise it to paper over a new direct .instance read.\n'
      '$actual\n',
    );
    stdout.writeln('Baseline updated to $actual.');
    return;
  }

  final baseline = _readBaseline();
  if (actual > baseline) {
    stderr.writeln(
      'SM-7 LearningProgramRepository.instance ratchet FAILED '
      '(AUD-scheduler-23) — "$_needle" occurs $actual time(s) under test/, '
      'up from the tracked baseline of $baseline. SM-7 bans global/static '
      'mutable singletons; LearningProgramRepository.instance is '
      "@Deprecated('Use learningProgramRepositoryProvider via Riverpod "
      "instead') and must not gain new direct readers. Override "
      'learningProgramRepositoryProvider on a ProviderContainer/ProviderScope '
      'instead. If you deliberately migrated call site(s) OFF the singleton '
      'and lowered the count, re-run with --update-baseline to lock the win '
      'in (see DNI-446 for the migration backlog).',
    );
    exit(1);
  }

  stdout.writeln(
    'SM-7 LearningProgramRepository.instance ratchet passed — $actual '
    'occurrence(s) of "$_needle" under test/ (tracked baseline: $baseline, '
    'backlog paydown tracked at DNI-446).',
  );
}
