/// Database-schema table-list generator — AUD-docs-15 / AUD-docs-16.
///
/// architecture.md's "Database Schema — Generated Table List" section (and
/// its summary line above it) has claimed to be "generated by
/// `tool/gen_arch_tables.dart`... Run `make gen-arch-tables` to regenerate"
/// since at least schema v14 — but neither the script nor the Makefile
/// target existed. The claimed numbers (v14, 21 User DB tables/22 DAOs, 27
/// tables total) drifted arbitrarily far from reality (v35, 24 tables/24
/// DAOs, 30 tables total) with no mechanical way to catch it. This script
/// makes the doc's own claim true.
///
/// Reads the three `@DriftDatabase`-annotated classes directly (not
/// generated `.g.dart` code, which doesn't preserve column declaration
/// order/shape in an easily-parseable way) and the individual `Table`
/// subclass files under `lib/core/database/tables/` and
/// `lib/core/database/registry/tables/`, counting `*Column get` getter
/// declarations per table (a regex/brace-scan heuristic, not a full Dart
/// parser — sufficient for this repo's consistently-declarative table
/// files; see `_countColumns`).
///
/// Usage (from `learning_tracker/`):
///   dart run tool/gen_arch_tables.dart              # print the markdown table + summary line
///   dart run tool/gen_arch_tables.dart --check       # exit 1 if architecture.md's committed
///                                                     # table/summary content differs from
///                                                     # freshly-generated output
library;

import 'dart:io';

class _DbSpec {
  _DbSpec({
    required this.label,
    required this.databaseFile,
    required this.schemaVersionPattern,
    required this.tableSearchDirs,
  });

  final String label;
  final String databaseFile;
  final RegExp schemaVersionPattern;
  final List<String> tableSearchDirs;
}

final _dbSpecs = [
  _DbSpec(
    label: 'Content DB',
    databaseFile: 'lib/core/database/content/content_database.dart',
    schemaVersionPattern: RegExp(
      r'static const int expectedSchemaVersion\s*=\s*(\d+);',
    ),
    tableSearchDirs: ['lib/core/database/tables'],
  ),
  _DbSpec(
    label: 'Registry DB',
    databaseFile: 'lib/core/database/registry/device_registry_database.dart',
    schemaVersionPattern: RegExp(r'int get schemaVersion\s*=>\s*(\d+);'),
    tableSearchDirs: ['lib/core/database/registry/tables'],
  ),
];

final _tablesListPattern = RegExp(r'tables:\s*\[([^\]]*)\]', dotAll: true);
final _daosListPattern = RegExp(r'daos:\s*\[([^\]]*)\]', dotAll: true);
final _identifierPattern = RegExp(r'^[A-Z][A-Za-z0-9_]*$');
final _columnGetterPattern = RegExp(
  r'^\s*(Int|Text|Bool|DateTime|Real|Blob)Column(<[^>]*>)?\s+get\s+\w+',
);

List<String> _extractIdentifierList(String source, RegExp listPattern) {
  final match = listPattern.firstMatch(source);
  if (match == null) return const [];
  final body = match.group(1)!;
  // Strip full-line (and trailing) `//` comments line-by-line BEFORE
  // splitting on commas — a comment on its own line (e.g. `// WS7: ...`)
  // sits in the same comma-delimited token as the identifier on the
  // following line, so a naive single-token indexOf('//') truncation would
  // eat the real identifier along with the comment.
  final withoutComments = body
      .split('\n')
      .map((line) {
        final idx = line.indexOf('//');
        return idx == -1 ? line : line.substring(0, idx);
      })
      .join('\n');
  return withoutComments
      .split(',')
      .map((t) => t.trim())
      .where((t) => _identifierPattern.hasMatch(t))
      .toList();
}

/// Finds `class <name> extends Table {` in any file under [searchDirs] and
/// counts `*Column get` declarations within that class body (brace-depth
/// scan from the opening `{` to its matching close).
int? _countColumns(String tableName, List<String> searchDirs) {
  final classPattern = RegExp('class\\s+$tableName\\s+extends\\s+Table\\s*\\{');
  for (final dirPath in searchDirs) {
    final dir = Directory(dirPath);
    if (!dir.existsSync()) continue;
    for (final entity in dir.listSync()) {
      if (entity is! File || !entity.path.endsWith('.dart')) continue;
      final content = entity.readAsStringSync();
      final match = classPattern.firstMatch(content);
      if (match == null) continue;

      var depth = 0;
      var i = match.end - 1; // position of the opening '{'
      var bodyStart = -1;
      for (; i < content.length; i++) {
        final ch = content[i];
        if (ch == '{') {
          depth++;
          if (bodyStart == -1) bodyStart = i + 1;
        } else if (ch == '}') {
          depth--;
          if (depth == 0) break;
        }
      }
      final body = content.substring(bodyStart, i);
      final columnCount = body
          .split('\n')
          .where((line) => _columnGetterPattern.hasMatch(line))
          .length;
      return columnCount;
    }
  }
  return null; // not found — caller reports as a generation error
}

class _TableRow {
  _TableRow(this.dbLabel, this.tableName, this.columns);
  final String dbLabel;
  final String tableName;
  final int? columns;
}

class _DbSummary {
  _DbSummary({
    required this.label,
    required this.fileLabel,
    required this.schemaVersion,
    required this.tableCount,
    required this.daoCount,
  });
  final String label;
  final String fileLabel;
  final String schemaVersion;
  final int tableCount;
  final int? daoCount; // null = "— (inline)" (no daos: list, e.g. Registry DB)
}

void main(List<String> args) {
  final check = args.contains('--check');

  final rows = <_TableRow>[];
  final summaries = <_DbSummary>[];

  for (final spec in _dbSpecs) {
    final file = File(spec.databaseFile);
    if (!file.existsSync()) {
      stderr.writeln(
        'ERROR: ${spec.databaseFile} not found — run from learning_tracker/',
      );
      exit(2);
    }
    final content = file.readAsStringSync();

    final versionMatch = spec.schemaVersionPattern.firstMatch(content);
    final schemaVersion = versionMatch?.group(1) ?? '?';

    final tableNames = _extractIdentifierList(content, _tablesListPattern);
    final daoNames = _extractIdentifierList(content, _daosListPattern);

    for (final tableName in tableNames) {
      final columns = _countColumns(tableName, spec.tableSearchDirs);
      rows.add(_TableRow(spec.label, tableName, columns));
    }

    summaries.add(
      _DbSummary(
        label: spec.label,
        fileLabel: spec.databaseFile,
        schemaVersion: schemaVersion,
        tableCount: tableNames.length,
        daoCount: daoNames.isEmpty ? null : daoNames.length,
      ),
    );
  }

  final buffer = StringBuffer()
    ..writeln('| Database | Schema Version | Tables | DAOs |')
    ..writeln('| --- | --- | --- | --- |');
  for (final s in summaries) {
    buffer.writeln(
      '| ${s.label} | **v${s.schemaVersion}** | ${s.tableCount} | '
      '${s.daoCount ?? "— (inline)"} |',
    );
  }
  buffer.writeln();
  buffer.writeln('| Database | Table | Columns |');
  buffer.writeln('| --- | --- | --- |');
  for (final r in rows) {
    buffer.writeln('| ${r.dbLabel} | ${r.tableName} | ${r.columns ?? "?"} |');
  }
  final total = rows.length;
  final byDb = <String, int>{};
  for (final r in rows) {
    byDb[r.dbLabel] = (byDb[r.dbLabel] ?? 0) + 1;
  }
  final totalLine =
      '_Generated by `tool/gen_arch_tables.dart`. Total: '
      '${byDb.entries.map((e) => "${e.value} ${e.key}").join(" + ")} = '
      '$total tables._';
  buffer.writeln();
  buffer.writeln(totalLine);

  final unresolved = rows.where((r) => r.columns == null).toList();
  if (unresolved.isNotEmpty) {
    stderr.writeln(
      'WARNING: could not locate/parse ${unresolved.length} table class(es): '
      '${unresolved.map((r) => r.tableName).join(", ")}',
    );
  }

  if (check) {
    const archPath = '../docs/architecture.md';
    final archFile = File(archPath);
    if (!archFile.existsSync()) {
      stderr.writeln('ERROR: $archPath not found');
      exit(2);
    }
    final archContent = archFile.readAsStringSync();
    if (!archContent.contains(totalLine)) {
      stderr.writeln(
        'AUD-docs-15/16 gen-arch-tables check FAILED: docs/architecture.md '
        'does not contain the freshly-generated total line:\n  $totalLine\n'
        'Run `dart run tool/gen_arch_tables.dart` and update '
        'docs/architecture.md (and any doc citing these counts) to match.',
      );
      exit(1);
    }
    stdout.writeln(
      'gen-arch-tables check OK: docs/architecture.md matches freshly-generated counts.',
    );
    return;
  }

  stdout.write(buffer.toString());
}
