import 'package:learning_tracker/core/enums/curriculum_id.dart';
import 'package:learning_tracker/core/exceptions/app_exception.dart';
import 'package:learning_tracker/core/network/sefaria/models/content_item.dart';
import 'package:learning_tracker/core/network/sefaria/models/curriculum_hierarchy_config.dart';

/// Repository for loading and accessing bundled curriculum content.
///
/// Content is loaded from JSON asset files generated by tool/seed_content.dart
/// at build time. This replaces the runtime Sefaria import.
abstract class ContentRepository {
  /// Get all content items for a curriculum.
  ///
  /// Lazily loads and parses the JSON file on first call, then caches in
  /// memory. Returns the full hierarchy (both containers and leaf nodes).
  ///
  /// Throws [ContentLoadException] if the JSON content is malformed (invalid
  /// JSON syntax, or another [Exception] surfaces while loading/parsing). A
  /// genuinely missing/unreadable asset file surfaces as a raw platform
  /// error instead of being downgraded to [ContentLoadException] — EH-4,
  /// AUD-content_browsing-09: that case indicates a content-bundling defect
  /// (every [CurriculumId] this method is called with is expected to ship
  /// an asset), not an ordinary recoverable content-load failure.
  Future<List<ContentItem>> getContentForCurriculum(CurriculumId curriculumId);

  /// Get the hierarchy configuration for a curriculum.
  ///
  /// Returns metadata about the hierarchy structure (level labels, depth, etc.).
  Future<CurriculumHierarchyConfig> getHierarchyConfig(
    CurriculumId curriculumId,
  );

  /// Filter content items by hierarchy level.
  ///
  /// Returns all items matching the specified level values. For example,
  /// filtering by `level1: 'Seder Zeraim'` returns all items in that seder.
  Future<List<ContentItem>> filterByLevel({
    required CurriculumId curriculumId,
    String? level1,
    String? level2,
    String? level3,
    String? level4,
  });

  /// Get content items filtered by curriculum scopes.
  ///
  /// [scopeLevel] is which hierarchy level scopes apply to (1-4).
  /// [scopeValues] are the selected values at that level.
  /// Returns only leaf items matching any of the scope values.
  /// If [scopeValues] is empty, returns all content (no filtering).
  Future<List<ContentItem>> getScopedContent({
    required CurriculumId curriculumId,
    required int scopeLevel,
    required List<String> scopeValues,
  });

  /// Search content by display name.
  ///
  /// Returns all items where displayNameHe or displayNameEn contains the
  /// query string (case-insensitive).
  Future<List<ContentItem>> search({
    required CurriculumId curriculumId,
    required String query,
  });

  /// Get a specific content item by its sefariaRef.
  Future<ContentItem?> getContentByRef({
    required CurriculumId curriculumId,
    required String sefariaRef,
  });
}

/// Exception thrown when content fails to load from assets.
class ContentLoadException extends NetworkException {
  const ContentLoadException(super.message, {super.cause});
}
