/// Rambam 3 Chapters — 339 entries per cycle.
/// Source: Sefaria-Data (github.com/Sefaria/Sefaria-Data)
///
/// Anchor: index 0 corresponds to 2018-09-01 (21 Elul 5778).
/// Cycle length: 339 days. Next cycles start every 339 days from anchor.
const rambam3ChaptersSequence = <String>[
  'Mishneh Torah, Transmission of the Oral Law 1-45',
  'Mishneh Torah, Positive Mitzvot 1-248',
  'Mishneh Torah, Negative Mitzvot 1-365',
  'Mishneh Torah, Overview of Mishneh Torah Contents 1-14',
  'Mishneh Torah, Foundations of the Torah 1-3',
  'Mishneh Torah, Foundations of the Torah 4-6',
  'Mishneh Torah, Foundations of the Torah 7-9',
  'Mishneh Torah, Foundations of the Torah 10; Mishneh Torah, Human Dispositions 1-2',
  'Mishneh Torah, Human Dispositions 3-5',
  'Mishneh Torah, Human Dispositions 6; Mishneh Torah, Torah Study 1',
  'Mishneh Torah, Torah Study 2-4',
  'Mishneh Torah, Torah Study 5-7',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 1-3',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 4-6',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 7-9',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 10-12',
  'Mishneh Torah, Repentance 1-3',
  'Mishneh Torah, Repentance 4-6',
  'Mishneh Torah, Repentance 7-9',
  'Mishneh Torah, Repentance 10; Mishneh Torah, Reading the Shema 1-2',
  'Mishneh Torah, Reading the Shema 3; Mishneh Torah, Prayer and the Priestly Blessing 1',
  'Mishneh Torah, Prayer and the Priestly Blessing 2-4',
  'Mishneh Torah, Prayer and the Priestly Blessing 5-7',
  'Mishneh Torah, Prayer and the Priestly Blessing 8-10',
  'Mishneh Torah, Prayer and the Priestly Blessing 11-13',
  'Mishneh Torah, Prayer and the Priestly Blessing 14; Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 1',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 2-4',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 5-7',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 8-10',
  'Mishneh Torah, Fringes 1-3',
  'Mishneh Torah, Blessings 1-3',
  'Mishneh Torah, Blessings 4-6',
  'Mishneh Torah, Blessings 7-9',
  'Mishneh Torah, Blessings 10; Mishneh Torah, Circumcision 1',
  'Mishneh Torah, Circumcision 2; Mishneh Torah, The Order of Prayer 1',
  'Mishneh Torah, The Order of Prayer 2-4',
  'Mishneh Torah, Sabbath 1-3',
  'Mishneh Torah, Sabbath 4-6',
  'Mishneh Torah, Sabbath 7-9',
  'Mishneh Torah, Sabbath 10-12',
  'Mishneh Torah, Sabbath 13-15',
  'Mishneh Torah, Sabbath 16-18',
  'Mishneh Torah, Sabbath 19-21',
  'Mishneh Torah, Sabbath 22-24',
  'Mishneh Torah, Sabbath 25-27',
  'Mishneh Torah, Sabbath 28-30',
  'Mishneh Torah, Eruvin 1-3',
  'Mishneh Torah, Eruvin 4-6',
  'Mishneh Torah, Eruvin 7; Mishneh Torah, Rest on the Tenth of Tishrei 1',
  'Mishneh Torah, Rest on the Tenth of Tishrei 2; Mishneh Torah, Rest on a Holiday 1',
  'Mishneh Torah, Rest on a Holiday 2-4',
  'Mishneh Torah, Rest on a Holiday 5-7',
  'Mishneh Torah, Rest on a Holiday 8; Mishneh Torah, Leavened and Unleavened Bread 1-2',
  'Mishneh Torah, Leavened and Unleavened Bread 3-5',
  'Mishneh Torah, Leavened and Unleavened Bread 6-8',
  'Mishneh Torah, Leavened and Unleavened Bread 9; Mishneh Torah, Shofar, Sukkah and Lulav 1-2',
  'Mishneh Torah, Shofar, Sukkah and Lulav 3-5',
  'Mishneh Torah, Shofar, Sukkah and Lulav 6-8',
  'Mishneh Torah, Sheqel Dues 1-3',
  'Mishneh Torah, Sheqel Dues 4; Mishneh Torah, Sanctification of the New Month 1-2',
  'Mishneh Torah, Sanctification of the New Month 3-5',
  'Mishneh Torah, Sanctification of the New Month 6-8',
  'Mishneh Torah, Sanctification of the New Month 9-11',
  'Mishneh Torah, Sanctification of the New Month 12-14',
  'Mishneh Torah, Sanctification of the New Month 15-17',
  'Mishneh Torah, Sanctification of the New Month 18; Mishneh Torah, Fasts 1',
  'Mishneh Torah, Fasts 2-4',
  'Mishneh Torah, Fasts 5; Mishneh Torah, Scroll of Esther and Hanukkah 1-2',
  'Mishneh Torah, Scroll of Esther and Hanukkah 3; Mishneh Torah, Marriage 1',
  'Mishneh Torah, Marriage 2-4',
  'Mishneh Torah, Marriage 5-7',
  'Mishneh Torah, Marriage 8-10',
  'Mishneh Torah, Marriage 11-13',
  'Mishneh Torah, Marriage 14-16',
  'Mishneh Torah, Marriage 17-19',
  'Mishneh Torah, Marriage 20-22',
  'Mishneh Torah, Marriage 23-25',
  'Mishneh Torah, Divorce 1-3',
  'Mishneh Torah, Divorce 4-6',
  'Mishneh Torah, Divorce 7-9',
  'Mishneh Torah, Divorce 10-12',
  'Mishneh Torah, Divorce 13; Mishneh Torah, Levirate Marriage and Release 1-2',
  'Mishneh Torah, Levirate Marriage and Release 3-5',
  'Mishneh Torah, Levirate Marriage and Release 6-8',
  'Mishneh Torah, Virgin Maiden 1-3',
  'Mishneh Torah, Woman Suspected of Infidelity 1-3',
  'Mishneh Torah, Woman Suspected of Infidelity 4; Mishneh Torah, Forbidden Intercourse 1-2',
  'Mishneh Torah, Forbidden Intercourse 3-5',
  'Mishneh Torah, Forbidden Intercourse 6-8',
  'Mishneh Torah, Forbidden Intercourse 9-11',
  'Mishneh Torah, Forbidden Intercourse 12-14',
  'Mishneh Torah, Forbidden Intercourse 15-17',
  'Mishneh Torah, Forbidden Intercourse 18-20',
  'Mishneh Torah, Forbidden Intercourse 21; Mishneh Torah, Forbidden Foods 1',
  'Mishneh Torah, Forbidden Foods 2-4',
  'Mishneh Torah, Forbidden Foods 5-7',
  'Mishneh Torah, Forbidden Foods 8-10',
  'Mishneh Torah, Forbidden Foods 11-13',
  'Mishneh Torah, Forbidden Foods 14-16',
  'Mishneh Torah, Forbidden Foods 17; Mishneh Torah, Ritual Slaughter 1-2',
  'Mishneh Torah, Ritual Slaughter 3-5',
  'Mishneh Torah, Ritual Slaughter 6-8',
  'Mishneh Torah, Ritual Slaughter 9-11',
  'Mishneh Torah, Ritual Slaughter 12-14',
  'Mishneh Torah, Oaths 1-3',
  'Mishneh Torah, Oaths 4-6',
  'Mishneh Torah, Oaths 7-9',
  'Mishneh Torah, Oaths 10-12',
  'Mishneh Torah, Vows 1-3',
  'Mishneh Torah, Vows 4-6',
  'Mishneh Torah, Vows 7-9',
  'Mishneh Torah, Vows 10-12',
  'Mishneh Torah, Vows 13; Mishneh Torah, Nazariteship 1-2',
  'Mishneh Torah, Nazariteship 3-5',
  'Mishneh Torah, Nazariteship 6-8',
  'Mishneh Torah, Nazariteship 9; Mishneh Torah, Appraisals and Devoted Property 1',
  'Mishneh Torah, Appraisals and Devoted Property 2-4',
  'Mishneh Torah, Appraisals and Devoted Property 5-7',
  'Mishneh Torah, Appraisals and Devoted Property 8; Mishneh Torah, Diverse Species 1-2',
  'Mishneh Torah, Diverse Species 3-5',
  'Mishneh Torah, Diverse Species 6-8',
  'Mishneh Torah, Diverse Species 9; Mishneh Torah, Gifts to the Poor 1',
  'Mishneh Torah, Gifts to the Poor 2-4',
  'Mishneh Torah, Gifts to the Poor 5-7',
  'Mishneh Torah, Gifts to the Poor 8-10',
  'Mishneh Torah, Heave Offerings 1-3',
  'Mishneh Torah, Heave Offerings 4-6',
  'Mishneh Torah, Heave Offerings 7-9',
  'Mishneh Torah, Heave Offerings 10-12',
  'Mishneh Torah, Heave Offerings 13-15',
  'Mishneh Torah, Tithes 1-3',
  'Mishneh Torah, Tithes 4-6',
  'Mishneh Torah, Tithes 7-9',
  'Mishneh Torah, Tithes 10-12',
  'Mishneh Torah, Tithes 13; Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 1',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 2-4',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 5-7',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 8-10',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 11; Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 1-2',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 3-5',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 6-8',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 9-11',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 12; Mishneh Torah, Sabbatical Year and the Jubilee 1-2',
  'Mishneh Torah, Sabbatical Year and the Jubilee 3-5',
  'Mishneh Torah, Sabbatical Year and the Jubilee 6-8',
  'Mishneh Torah, Sabbatical Year and the Jubilee 9-11',
  'Mishneh Torah, Sabbatical Year and the Jubilee 12; Mishneh Torah, The Chosen Temple 1',
  'Mishneh Torah, The Chosen Temple 2-4',
  'Mishneh Torah, The Chosen Temple 5-7',
  'Mishneh Torah, The Chosen Temple 8; Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 1-2',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 3-5',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 6-8',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 9; Mishneh Torah, Admission into the Sanctuary 1',
  'Mishneh Torah, Admission into the Sanctuary 2-4',
  'Mishneh Torah, Admission into the Sanctuary 5-7',
  'Mishneh Torah, Admission into the Sanctuary 8; Mishneh Torah, Things Forbidden on the Altar 1',
  'Mishneh Torah, Things Forbidden on the Altar 2-4',
  'Mishneh Torah, Things Forbidden on the Altar 5-7',
  'Mishneh Torah, Sacrificial Procedure 1-3',
  'Mishneh Torah, Sacrificial Procedure 4-6',
  'Mishneh Torah, Sacrificial Procedure 7-9',
  'Mishneh Torah, Sacrificial Procedure 10-12',
  'Mishneh Torah, Sacrificial Procedure 13-15',
  'Mishneh Torah, Sacrificial Procedure 16-18',
  'Mishneh Torah, Sacrificial Procedure 19; Mishneh Torah, Daily Offerings and Additional Offerings 1-2',
  'Mishneh Torah, Daily Offerings and Additional Offerings 3-5',
  'Mishneh Torah, Daily Offerings and Additional Offerings 6-8',
  'Mishneh Torah, Daily Offerings and Additional Offerings 9; Mishneh Torah, Sacrifices Rendered Unfit 1',
  'Mishneh Torah, Sacrifices Rendered Unfit 2-4',
  'Mishneh Torah, Sacrifices Rendered Unfit 5-7',
  'Mishneh Torah, Sacrifices Rendered Unfit 8-10',
  'Mishneh Torah, Sacrifices Rendered Unfit 11-13',
  'Mishneh Torah, Sacrifices Rendered Unfit 14-16',
  'Mishneh Torah, Sacrifices Rendered Unfit 17-19',
  'Mishneh Torah, Service on the Day of Atonement 1-3',
  'Mishneh Torah, Service on the Day of Atonement 4; Mishneh Torah, Trespass 1',
  'Mishneh Torah, Trespass 2-4',
  'Mishneh Torah, Trespass 5-7',
  'Mishneh Torah, Trespass 8; Mishneh Torah, Paschal Offering 1-2',
  'Mishneh Torah, Paschal Offering 3-5',
  'Mishneh Torah, Paschal Offering 6-8',
  'Mishneh Torah, Paschal Offering 9; Mishneh Torah, Festival Offering 1',
  'Mishneh Torah, Festival Offering 2; Mishneh Torah, Firstlings 1',
  'Mishneh Torah, Firstlings 2-4',
  'Mishneh Torah, Firstlings 5-7',
  'Mishneh Torah, Firstlings 8; Mishneh Torah, Offerings for Unintentional Transgressions 1-2',
  'Mishneh Torah, Offerings for Unintentional Transgressions 3-5',
  'Mishneh Torah, Offerings for Unintentional Transgressions 6-8',
  'Mishneh Torah, Offerings for Unintentional Transgressions 9-11',
  'Mishneh Torah, Offerings for Unintentional Transgressions 12-14',
  'Mishneh Torah, Offerings for Unintentional Transgressions 15; Mishneh Torah, Offerings for Those with Incomplete Atonement 1-2',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 3-5',
  'Mishneh Torah, Substitution 1-3',
  'Mishneh Torah, Substitution 4; Mishneh Torah, Defilement by a Corpse 1-2',
  'Mishneh Torah, Defilement by a Corpse 3-5',
  'Mishneh Torah, Defilement by a Corpse 6-8',
  'Mishneh Torah, Defilement by a Corpse 9-11',
  'Mishneh Torah, Defilement by a Corpse 12-14',
  'Mishneh Torah, Defilement by a Corpse 15-17',
  'Mishneh Torah, Defilement by a Corpse 18-20',
  'Mishneh Torah, Defilement by a Corpse 21-23',
  'Mishneh Torah, Defilement by a Corpse 24; Mishneh Torah, Red Heifer 1',
  'Mishneh Torah, Red Heifer 2-4',
  'Mishneh Torah, Red Heifer 5-7',
  'Mishneh Torah, Red Heifer 8-10',
  'Mishneh Torah, Red Heifer 11-13',
  'Mishneh Torah, Red Heifer 14; Mishneh Torah, Defilement by Leprosy 1',
  'Mishneh Torah, Defilement by Leprosy 2-4',
  'Mishneh Torah, Defilement by Leprosy 5-7',
  'Mishneh Torah, Defilement by Leprosy 8-10',
  'Mishneh Torah, Defilement by Leprosy 11-13',
  'Mishneh Torah, Defilement by Leprosy 14-16',
  'Mishneh Torah, Those Who Defile Bed or Seat 1-3',
  'Mishneh Torah, Those Who Defile Bed or Seat 4-6',
  'Mishneh Torah, Those Who Defile Bed or Seat 7-9',
  'Mishneh Torah, Those Who Defile Bed or Seat 10-12',
  'Mishneh Torah, Those Who Defile Bed or Seat 13; Mishneh Torah, Other Sources of Defilement 1-2',
  'Mishneh Torah, Other Sources of Defilement 3-5',
  'Mishneh Torah, Other Sources of Defilement 6-8',
  'Mishneh Torah, Other Sources of Defilement 9-11',
  'Mishneh Torah, Other Sources of Defilement 12-14',
  'Mishneh Torah, Other Sources of Defilement 15-17',
  'Mishneh Torah, Other Sources of Defilement 18-20',
  'Mishneh Torah, Defilement of Foods 1-3',
  'Mishneh Torah, Defilement of Foods 4-6',
  'Mishneh Torah, Defilement of Foods 7-9',
  'Mishneh Torah, Defilement of Foods 10-12',
  'Mishneh Torah, Defilement of Foods 13-15',
  'Mishneh Torah, Defilement of Foods 16; Mishneh Torah, Vessels 1-2',
  'Mishneh Torah, Vessels 3-5',
  'Mishneh Torah, Vessels 6-8',
  'Mishneh Torah, Vessels 9-11',
  'Mishneh Torah, Vessels 12-14',
  'Mishneh Torah, Vessels 15-17',
  'Mishneh Torah, Vessels 18-20',
  'Mishneh Torah, Vessels 21-23',
  'Mishneh Torah, Vessels 24-26',
  'Mishneh Torah, Vessels 27; Mishneh Torah, Immersion Pools 1',
  'Mishneh Torah, Immersion Pools 2-4',
  'Mishneh Torah, Immersion Pools 5-7',
  'Mishneh Torah, Immersion Pools 8-10',
  'Mishneh Torah, Immersion Pools 11; Mishneh Torah, Damages to Property 1-2',
  'Mishneh Torah, Damages to Property 3-5',
  'Mishneh Torah, Damages to Property 6-8',
  'Mishneh Torah, Damages to Property 9-11',
  'Mishneh Torah, Damages to Property 12-14',
  'Mishneh Torah, Theft 1-3',
  'Mishneh Torah, Theft 4-6',
  'Mishneh Torah, Theft 7-9',
  'Mishneh Torah, Robbery and Lost Property 1-3',
  'Mishneh Torah, Robbery and Lost Property 4-6',
  'Mishneh Torah, Robbery and Lost Property 7-9',
  'Mishneh Torah, Robbery and Lost Property 10-12',
  'Mishneh Torah, Robbery and Lost Property 13-15',
  'Mishneh Torah, Robbery and Lost Property 16-18',
  'Mishneh Torah, One Who Injures a Person or Property 1-3',
  'Mishneh Torah, One Who Injures a Person or Property 4-6',
  'Mishneh Torah, One Who Injures a Person or Property 7; Mishneh Torah, Murderer and the Preservation of Life 1',
  'Mishneh Torah, Murderer and the Preservation of Life 2-4',
  'Mishneh Torah, Murderer and the Preservation of Life 5-7',
  'Mishneh Torah, Murderer and the Preservation of Life 8-10',
  'Mishneh Torah, Murderer and the Preservation of Life 11-13',
  'Mishneh Torah, Sales 1-3',
  'Mishneh Torah, Sales 4-6',
  'Mishneh Torah, Sales 7-9',
  'Mishneh Torah, Sales 10-12',
  'Mishneh Torah, Sales 13-15',
  'Mishneh Torah, Sales 16-18',
  'Mishneh Torah, Sales 19-21',
  'Mishneh Torah, Sales 22-24',
  'Mishneh Torah, Sales 25-27',
  'Mishneh Torah, Sales 28-30',
  'Mishneh Torah, Ownerless Property and Gifts 1-3',
  'Mishneh Torah, Ownerless Property and Gifts 4-6',
  'Mishneh Torah, Ownerless Property and Gifts 7-9',
  'Mishneh Torah, Ownerless Property and Gifts 10-12',
  'Mishneh Torah, Neighbors 1-3',
  'Mishneh Torah, Neighbors 4-6',
  'Mishneh Torah, Neighbors 7-9',
  'Mishneh Torah, Neighbors 10-12',
  'Mishneh Torah, Neighbors 13; Mishneh Torah, Agents and Partners 1',
  'Mishneh Torah, Agents and Partners 2-4',
  'Mishneh Torah, Agents and Partners 5-7',
  'Mishneh Torah, Agents and Partners 8-10',
  'Mishneh Torah, Slaves 1-3',
  'Mishneh Torah, Slaves 4-6',
  'Mishneh Torah, Slaves 7-9',
  'Mishneh Torah, Hiring 1-3',
  'Mishneh Torah, Hiring 4-6',
  'Mishneh Torah, Hiring 7-9',
  'Mishneh Torah, Hiring 10-12',
  'Mishneh Torah, Hiring 13; Mishneh Torah, Borrowing and Deposit 1-2',
  'Mishneh Torah, Borrowing and Deposit 3-5',
  'Mishneh Torah, Borrowing and Deposit 6-8',
  'Mishneh Torah, Creditor and Debtor 1-3',
  'Mishneh Torah, Creditor and Debtor 4-6',
  'Mishneh Torah, Creditor and Debtor 7-9',
  'Mishneh Torah, Creditor and Debtor 10-12',
  'Mishneh Torah, Creditor and Debtor 13-15',
  'Mishneh Torah, Creditor and Debtor 16-18',
  'Mishneh Torah, Creditor and Debtor 19-21',
  'Mishneh Torah, Creditor and Debtor 22-24',
  'Mishneh Torah, Creditor and Debtor 25-27',
  'Mishneh Torah, Plaintiff and Defendant 1-3',
  'Mishneh Torah, Plaintiff and Defendant 4-6',
  'Mishneh Torah, Plaintiff and Defendant 7-9',
  'Mishneh Torah, Plaintiff and Defendant 10-12',
  'Mishneh Torah, Plaintiff and Defendant 13-15',
  'Mishneh Torah, Plaintiff and Defendant 16; Mishneh Torah, Inheritances 1-2',
  'Mishneh Torah, Inheritances 3-5',
  'Mishneh Torah, Inheritances 6-8',
  'Mishneh Torah, Inheritances 9-11',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 1-3',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 4-6',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 7-9',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 10-12',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 13-15',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 16-18',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 19-21',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 22-24',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 25; Mishneh Torah, Testimony 1',
  'Mishneh Torah, Testimony 2-4',
  'Mishneh Torah, Testimony 5-7',
  'Mishneh Torah, Testimony 8-10',
  'Mishneh Torah, Testimony 11-13',
  'Mishneh Torah, Testimony 14-16',
  'Mishneh Torah, Testimony 17-19',
  'Mishneh Torah, Testimony 20-22',
  'Mishneh Torah, Rebels 1-3',
  'Mishneh Torah, Rebels 4-6',
  'Mishneh Torah, Rebels 7; Mishneh Torah, Mourning 1-2',
  'Mishneh Torah, Mourning 3-5',
  'Mishneh Torah, Mourning 6-8',
  'Mishneh Torah, Mourning 9-11',
  'Mishneh Torah, Mourning 12-14',
  'Mishneh Torah, Kings and Wars 1-3',
  'Mishneh Torah, Kings and Wars 4-6',
  'Mishneh Torah, Kings and Wars 7-9',
  'Mishneh Torah, Kings and Wars 10-12',
];
