/// Rambam 1 Chapter — 979 entries per cycle.
/// Source: Derived from Sefaria-Data Daily_Rambam_schedule_3_chapters.csv
///
/// Anchor: index 0 corresponds to 2018-09-05 (25 Elul 5778),
/// which is 4 days after the 3-chapter cycle start (intro days excluded).
/// Cycle length: 979 days.
const rambam1ChapterSequence = <String>[
  'Mishneh Torah, Foundations of the Torah 1',
  'Mishneh Torah, Foundations of the Torah 2',
  'Mishneh Torah, Foundations of the Torah 3',
  'Mishneh Torah, Foundations of the Torah 4',
  'Mishneh Torah, Foundations of the Torah 5',
  'Mishneh Torah, Foundations of the Torah 6',
  'Mishneh Torah, Foundations of the Torah 7',
  'Mishneh Torah, Foundations of the Torah 8',
  'Mishneh Torah, Foundations of the Torah 9',
  'Mishneh Torah, Foundations of the Torah 10',
  'Mishneh Torah, Human Dispositions 1',
  'Mishneh Torah, Human Dispositions 2',
  'Mishneh Torah, Human Dispositions 3',
  'Mishneh Torah, Human Dispositions 4',
  'Mishneh Torah, Human Dispositions 5',
  'Mishneh Torah, Human Dispositions 6',
  'Mishneh Torah, Torah Study 1',
  'Mishneh Torah, Torah Study 2',
  'Mishneh Torah, Torah Study 3',
  'Mishneh Torah, Torah Study 4',
  'Mishneh Torah, Torah Study 5',
  'Mishneh Torah, Torah Study 6',
  'Mishneh Torah, Torah Study 7',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 1',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 2',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 3',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 4',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 5',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 6',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 7',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 8',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 9',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 10',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 11',
  'Mishneh Torah, Foreign Worship and Customs of the Nations 12',
  'Mishneh Torah, Repentance 1',
  'Mishneh Torah, Repentance 2',
  'Mishneh Torah, Repentance 3',
  'Mishneh Torah, Repentance 4',
  'Mishneh Torah, Repentance 5',
  'Mishneh Torah, Repentance 6',
  'Mishneh Torah, Repentance 7',
  'Mishneh Torah, Repentance 8',
  'Mishneh Torah, Repentance 9',
  'Mishneh Torah, Repentance 10',
  'Mishneh Torah, Reading the Shema 1',
  'Mishneh Torah, Reading the Shema 2',
  'Mishneh Torah, Reading the Shema 3',
  'Mishneh Torah, Prayer and the Priestly Blessing 1',
  'Mishneh Torah, Prayer and the Priestly Blessing 2',
  'Mishneh Torah, Prayer and the Priestly Blessing 3',
  'Mishneh Torah, Prayer and the Priestly Blessing 4',
  'Mishneh Torah, Prayer and the Priestly Blessing 5',
  'Mishneh Torah, Prayer and the Priestly Blessing 6',
  'Mishneh Torah, Prayer and the Priestly Blessing 7',
  'Mishneh Torah, Prayer and the Priestly Blessing 8',
  'Mishneh Torah, Prayer and the Priestly Blessing 9',
  'Mishneh Torah, Prayer and the Priestly Blessing 10',
  'Mishneh Torah, Prayer and the Priestly Blessing 11',
  'Mishneh Torah, Prayer and the Priestly Blessing 12',
  'Mishneh Torah, Prayer and the Priestly Blessing 13',
  'Mishneh Torah, Prayer and the Priestly Blessing 14',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 1',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 2',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 3',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 4',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 5',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 6',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 7',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 8',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 9',
  'Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll 10',
  'Mishneh Torah, Fringes 1',
  'Mishneh Torah, Fringes 2',
  'Mishneh Torah, Fringes 3',
  'Mishneh Torah, Blessings 1',
  'Mishneh Torah, Blessings 2',
  'Mishneh Torah, Blessings 3',
  'Mishneh Torah, Blessings 4',
  'Mishneh Torah, Blessings 5',
  'Mishneh Torah, Blessings 6',
  'Mishneh Torah, Blessings 7',
  'Mishneh Torah, Blessings 8',
  'Mishneh Torah, Blessings 9',
  'Mishneh Torah, Blessings 10',
  'Mishneh Torah, Circumcision 1',
  'Mishneh Torah, Circumcision 2',
  'Mishneh Torah, The Order of Prayer 1',
  'Mishneh Torah, The Order of Prayer 2',
  'Mishneh Torah, The Order of Prayer 3',
  'Mishneh Torah, The Order of Prayer 4',
  'Mishneh Torah, Sabbath 1',
  'Mishneh Torah, Sabbath 2',
  'Mishneh Torah, Sabbath 3',
  'Mishneh Torah, Sabbath 4',
  'Mishneh Torah, Sabbath 5',
  'Mishneh Torah, Sabbath 6',
  'Mishneh Torah, Sabbath 7',
  'Mishneh Torah, Sabbath 8',
  'Mishneh Torah, Sabbath 9',
  'Mishneh Torah, Sabbath 10',
  'Mishneh Torah, Sabbath 11',
  'Mishneh Torah, Sabbath 12',
  'Mishneh Torah, Sabbath 13',
  'Mishneh Torah, Sabbath 14',
  'Mishneh Torah, Sabbath 15',
  'Mishneh Torah, Sabbath 16',
  'Mishneh Torah, Sabbath 17',
  'Mishneh Torah, Sabbath 18',
  'Mishneh Torah, Sabbath 19',
  'Mishneh Torah, Sabbath 20',
  'Mishneh Torah, Sabbath 21',
  'Mishneh Torah, Sabbath 22',
  'Mishneh Torah, Sabbath 23',
  'Mishneh Torah, Sabbath 24',
  'Mishneh Torah, Sabbath 25',
  'Mishneh Torah, Sabbath 26',
  'Mishneh Torah, Sabbath 27',
  'Mishneh Torah, Sabbath 28',
  'Mishneh Torah, Sabbath 29',
  'Mishneh Torah, Sabbath 30',
  'Mishneh Torah, Eruvin 1',
  'Mishneh Torah, Eruvin 2',
  'Mishneh Torah, Eruvin 3',
  'Mishneh Torah, Eruvin 4',
  'Mishneh Torah, Eruvin 5',
  'Mishneh Torah, Eruvin 6',
  'Mishneh Torah, Eruvin 7',
  'Mishneh Torah, Rest on the Tenth of Tishrei 1',
  'Mishneh Torah, Rest on the Tenth of Tishrei 2',
  'Mishneh Torah, Rest on a Holiday 1',
  'Mishneh Torah, Rest on a Holiday 2',
  'Mishneh Torah, Rest on a Holiday 3',
  'Mishneh Torah, Rest on a Holiday 4',
  'Mishneh Torah, Rest on a Holiday 5',
  'Mishneh Torah, Rest on a Holiday 6',
  'Mishneh Torah, Rest on a Holiday 7',
  'Mishneh Torah, Rest on a Holiday 8',
  'Mishneh Torah, Leavened and Unleavened Bread 1',
  'Mishneh Torah, Leavened and Unleavened Bread 2',
  'Mishneh Torah, Leavened and Unleavened Bread 3',
  'Mishneh Torah, Leavened and Unleavened Bread 4',
  'Mishneh Torah, Leavened and Unleavened Bread 5',
  'Mishneh Torah, Leavened and Unleavened Bread 6',
  'Mishneh Torah, Leavened and Unleavened Bread 7',
  'Mishneh Torah, Leavened and Unleavened Bread 8',
  'Mishneh Torah, Leavened and Unleavened Bread 9',
  'Mishneh Torah, Shofar, Sukkah and Lulav 1',
  'Mishneh Torah, Shofar, Sukkah and Lulav 2',
  'Mishneh Torah, Shofar, Sukkah and Lulav 3',
  'Mishneh Torah, Shofar, Sukkah and Lulav 4',
  'Mishneh Torah, Shofar, Sukkah and Lulav 5',
  'Mishneh Torah, Shofar, Sukkah and Lulav 6',
  'Mishneh Torah, Shofar, Sukkah and Lulav 7',
  'Mishneh Torah, Shofar, Sukkah and Lulav 8',
  'Mishneh Torah, Sheqel Dues 1',
  'Mishneh Torah, Sheqel Dues 2',
  'Mishneh Torah, Sheqel Dues 3',
  'Mishneh Torah, Sheqel Dues 4',
  'Mishneh Torah, Sanctification of the New Month 1',
  'Mishneh Torah, Sanctification of the New Month 2',
  'Mishneh Torah, Sanctification of the New Month 3',
  'Mishneh Torah, Sanctification of the New Month 4',
  'Mishneh Torah, Sanctification of the New Month 5',
  'Mishneh Torah, Sanctification of the New Month 6',
  'Mishneh Torah, Sanctification of the New Month 7',
  'Mishneh Torah, Sanctification of the New Month 8',
  'Mishneh Torah, Sanctification of the New Month 9',
  'Mishneh Torah, Sanctification of the New Month 10',
  'Mishneh Torah, Sanctification of the New Month 11',
  'Mishneh Torah, Sanctification of the New Month 12',
  'Mishneh Torah, Sanctification of the New Month 13',
  'Mishneh Torah, Sanctification of the New Month 14',
  'Mishneh Torah, Sanctification of the New Month 15',
  'Mishneh Torah, Sanctification of the New Month 16',
  'Mishneh Torah, Sanctification of the New Month 17',
  'Mishneh Torah, Sanctification of the New Month 18',
  'Mishneh Torah, Fasts 1',
  'Mishneh Torah, Fasts 2',
  'Mishneh Torah, Fasts 3',
  'Mishneh Torah, Fasts 4',
  'Mishneh Torah, Fasts 5',
  'Mishneh Torah, Scroll of Esther and Hanukkah 1',
  'Mishneh Torah, Scroll of Esther and Hanukkah 2',
  'Mishneh Torah, Scroll of Esther and Hanukkah 3',
  'Mishneh Torah, Marriage 1',
  'Mishneh Torah, Marriage 2',
  'Mishneh Torah, Marriage 3',
  'Mishneh Torah, Marriage 4',
  'Mishneh Torah, Marriage 5',
  'Mishneh Torah, Marriage 6',
  'Mishneh Torah, Marriage 7',
  'Mishneh Torah, Marriage 8',
  'Mishneh Torah, Marriage 9',
  'Mishneh Torah, Marriage 10',
  'Mishneh Torah, Marriage 11',
  'Mishneh Torah, Marriage 12',
  'Mishneh Torah, Marriage 13',
  'Mishneh Torah, Marriage 14',
  'Mishneh Torah, Marriage 15',
  'Mishneh Torah, Marriage 16',
  'Mishneh Torah, Marriage 17',
  'Mishneh Torah, Marriage 18',
  'Mishneh Torah, Marriage 19',
  'Mishneh Torah, Marriage 20',
  'Mishneh Torah, Marriage 21',
  'Mishneh Torah, Marriage 22',
  'Mishneh Torah, Marriage 23',
  'Mishneh Torah, Marriage 24',
  'Mishneh Torah, Marriage 25',
  'Mishneh Torah, Divorce 1',
  'Mishneh Torah, Divorce 2',
  'Mishneh Torah, Divorce 3',
  'Mishneh Torah, Divorce 4',
  'Mishneh Torah, Divorce 5',
  'Mishneh Torah, Divorce 6',
  'Mishneh Torah, Divorce 7',
  'Mishneh Torah, Divorce 8',
  'Mishneh Torah, Divorce 9',
  'Mishneh Torah, Divorce 10',
  'Mishneh Torah, Divorce 11',
  'Mishneh Torah, Divorce 12',
  'Mishneh Torah, Divorce 13',
  'Mishneh Torah, Levirate Marriage and Release 1',
  'Mishneh Torah, Levirate Marriage and Release 2',
  'Mishneh Torah, Levirate Marriage and Release 3',
  'Mishneh Torah, Levirate Marriage and Release 4',
  'Mishneh Torah, Levirate Marriage and Release 5',
  'Mishneh Torah, Levirate Marriage and Release 6',
  'Mishneh Torah, Levirate Marriage and Release 7',
  'Mishneh Torah, Levirate Marriage and Release 8',
  'Mishneh Torah, Virgin Maiden 1',
  'Mishneh Torah, Virgin Maiden 2',
  'Mishneh Torah, Virgin Maiden 3',
  'Mishneh Torah, Woman Suspected of Infidelity 1',
  'Mishneh Torah, Woman Suspected of Infidelity 2',
  'Mishneh Torah, Woman Suspected of Infidelity 3',
  'Mishneh Torah, Woman Suspected of Infidelity 4',
  'Mishneh Torah, Forbidden Intercourse 1',
  'Mishneh Torah, Forbidden Intercourse 2',
  'Mishneh Torah, Forbidden Intercourse 3',
  'Mishneh Torah, Forbidden Intercourse 4',
  'Mishneh Torah, Forbidden Intercourse 5',
  'Mishneh Torah, Forbidden Intercourse 6',
  'Mishneh Torah, Forbidden Intercourse 7',
  'Mishneh Torah, Forbidden Intercourse 8',
  'Mishneh Torah, Forbidden Intercourse 9',
  'Mishneh Torah, Forbidden Intercourse 10',
  'Mishneh Torah, Forbidden Intercourse 11',
  'Mishneh Torah, Forbidden Intercourse 12',
  'Mishneh Torah, Forbidden Intercourse 13',
  'Mishneh Torah, Forbidden Intercourse 14',
  'Mishneh Torah, Forbidden Intercourse 15',
  'Mishneh Torah, Forbidden Intercourse 16',
  'Mishneh Torah, Forbidden Intercourse 17',
  'Mishneh Torah, Forbidden Intercourse 18',
  'Mishneh Torah, Forbidden Intercourse 19',
  'Mishneh Torah, Forbidden Intercourse 20',
  'Mishneh Torah, Forbidden Intercourse 21',
  'Mishneh Torah, Forbidden Foods 1',
  'Mishneh Torah, Forbidden Foods 2',
  'Mishneh Torah, Forbidden Foods 3',
  'Mishneh Torah, Forbidden Foods 4',
  'Mishneh Torah, Forbidden Foods 5',
  'Mishneh Torah, Forbidden Foods 6',
  'Mishneh Torah, Forbidden Foods 7',
  'Mishneh Torah, Forbidden Foods 8',
  'Mishneh Torah, Forbidden Foods 9',
  'Mishneh Torah, Forbidden Foods 10',
  'Mishneh Torah, Forbidden Foods 11',
  'Mishneh Torah, Forbidden Foods 12',
  'Mishneh Torah, Forbidden Foods 13',
  'Mishneh Torah, Forbidden Foods 14',
  'Mishneh Torah, Forbidden Foods 15',
  'Mishneh Torah, Forbidden Foods 16',
  'Mishneh Torah, Forbidden Foods 17',
  'Mishneh Torah, Ritual Slaughter 1',
  'Mishneh Torah, Ritual Slaughter 2',
  'Mishneh Torah, Ritual Slaughter 3',
  'Mishneh Torah, Ritual Slaughter 4',
  'Mishneh Torah, Ritual Slaughter 5',
  'Mishneh Torah, Ritual Slaughter 6',
  'Mishneh Torah, Ritual Slaughter 7',
  'Mishneh Torah, Ritual Slaughter 8',
  'Mishneh Torah, Ritual Slaughter 9',
  'Mishneh Torah, Ritual Slaughter 10',
  'Mishneh Torah, Ritual Slaughter 11',
  'Mishneh Torah, Ritual Slaughter 12',
  'Mishneh Torah, Ritual Slaughter 13',
  'Mishneh Torah, Ritual Slaughter 14',
  'Mishneh Torah, Oaths 1',
  'Mishneh Torah, Oaths 2',
  'Mishneh Torah, Oaths 3',
  'Mishneh Torah, Oaths 4',
  'Mishneh Torah, Oaths 5',
  'Mishneh Torah, Oaths 6',
  'Mishneh Torah, Oaths 7',
  'Mishneh Torah, Oaths 8',
  'Mishneh Torah, Oaths 9',
  'Mishneh Torah, Oaths 10',
  'Mishneh Torah, Oaths 11',
  'Mishneh Torah, Oaths 12',
  'Mishneh Torah, Vows 1',
  'Mishneh Torah, Vows 2',
  'Mishneh Torah, Vows 3',
  'Mishneh Torah, Vows 4',
  'Mishneh Torah, Vows 5',
  'Mishneh Torah, Vows 6',
  'Mishneh Torah, Vows 7',
  'Mishneh Torah, Vows 8',
  'Mishneh Torah, Vows 9',
  'Mishneh Torah, Vows 10',
  'Mishneh Torah, Vows 11',
  'Mishneh Torah, Vows 12',
  'Mishneh Torah, Vows 13',
  'Mishneh Torah, Nazariteship 1',
  'Mishneh Torah, Nazariteship 2',
  'Mishneh Torah, Nazariteship 3',
  'Mishneh Torah, Nazariteship 4',
  'Mishneh Torah, Nazariteship 5',
  'Mishneh Torah, Nazariteship 6',
  'Mishneh Torah, Nazariteship 7',
  'Mishneh Torah, Nazariteship 8',
  'Mishneh Torah, Nazariteship 9',
  'Mishneh Torah, Appraisals and Devoted Property 1',
  'Mishneh Torah, Appraisals and Devoted Property 2',
  'Mishneh Torah, Appraisals and Devoted Property 3',
  'Mishneh Torah, Appraisals and Devoted Property 4',
  'Mishneh Torah, Appraisals and Devoted Property 5',
  'Mishneh Torah, Appraisals and Devoted Property 6',
  'Mishneh Torah, Appraisals and Devoted Property 7',
  'Mishneh Torah, Appraisals and Devoted Property 8',
  'Mishneh Torah, Diverse Species 1',
  'Mishneh Torah, Diverse Species 2',
  'Mishneh Torah, Diverse Species 3',
  'Mishneh Torah, Diverse Species 4',
  'Mishneh Torah, Diverse Species 5',
  'Mishneh Torah, Diverse Species 6',
  'Mishneh Torah, Diverse Species 7',
  'Mishneh Torah, Diverse Species 8',
  'Mishneh Torah, Diverse Species 9',
  'Mishneh Torah, Gifts to the Poor 1',
  'Mishneh Torah, Gifts to the Poor 2',
  'Mishneh Torah, Gifts to the Poor 3',
  'Mishneh Torah, Gifts to the Poor 4',
  'Mishneh Torah, Gifts to the Poor 5',
  'Mishneh Torah, Gifts to the Poor 6',
  'Mishneh Torah, Gifts to the Poor 7',
  'Mishneh Torah, Gifts to the Poor 8',
  'Mishneh Torah, Gifts to the Poor 9',
  'Mishneh Torah, Gifts to the Poor 10',
  'Mishneh Torah, Heave Offerings 1',
  'Mishneh Torah, Heave Offerings 2',
  'Mishneh Torah, Heave Offerings 3',
  'Mishneh Torah, Heave Offerings 4',
  'Mishneh Torah, Heave Offerings 5',
  'Mishneh Torah, Heave Offerings 6',
  'Mishneh Torah, Heave Offerings 7',
  'Mishneh Torah, Heave Offerings 8',
  'Mishneh Torah, Heave Offerings 9',
  'Mishneh Torah, Heave Offerings 10',
  'Mishneh Torah, Heave Offerings 11',
  'Mishneh Torah, Heave Offerings 12',
  'Mishneh Torah, Heave Offerings 13',
  'Mishneh Torah, Heave Offerings 14',
  'Mishneh Torah, Heave Offerings 15',
  'Mishneh Torah, Tithes 1',
  'Mishneh Torah, Tithes 2',
  'Mishneh Torah, Tithes 3',
  'Mishneh Torah, Tithes 4',
  'Mishneh Torah, Tithes 5',
  'Mishneh Torah, Tithes 6',
  'Mishneh Torah, Tithes 7',
  'Mishneh Torah, Tithes 8',
  'Mishneh Torah, Tithes 9',
  'Mishneh Torah, Tithes 10',
  'Mishneh Torah, Tithes 11',
  'Mishneh Torah, Tithes 12',
  'Mishneh Torah, Tithes 13',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 1',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 2',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 3',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 4',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 5',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 6',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 7',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 8',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 9',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 10',
  'Mishneh Torah, Second Tithes and Fourth Year\'s Fruit 11',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 1',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 2',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 3',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 4',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 5',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 6',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 7',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 8',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 9',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 10',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 11',
  'Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary 12',
  'Mishneh Torah, Sabbatical Year and the Jubilee 1',
  'Mishneh Torah, Sabbatical Year and the Jubilee 2',
  'Mishneh Torah, Sabbatical Year and the Jubilee 3',
  'Mishneh Torah, Sabbatical Year and the Jubilee 4',
  'Mishneh Torah, Sabbatical Year and the Jubilee 5',
  'Mishneh Torah, Sabbatical Year and the Jubilee 6',
  'Mishneh Torah, Sabbatical Year and the Jubilee 7',
  'Mishneh Torah, Sabbatical Year and the Jubilee 8',
  'Mishneh Torah, Sabbatical Year and the Jubilee 9',
  'Mishneh Torah, Sabbatical Year and the Jubilee 10',
  'Mishneh Torah, Sabbatical Year and the Jubilee 11',
  'Mishneh Torah, Sabbatical Year and the Jubilee 12',
  'Mishneh Torah, The Chosen Temple 1',
  'Mishneh Torah, The Chosen Temple 2',
  'Mishneh Torah, The Chosen Temple 3',
  'Mishneh Torah, The Chosen Temple 4',
  'Mishneh Torah, The Chosen Temple 5',
  'Mishneh Torah, The Chosen Temple 6',
  'Mishneh Torah, The Chosen Temple 7',
  'Mishneh Torah, The Chosen Temple 8',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 1',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 2',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 3',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 4',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 5',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 6',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 7',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 8',
  'Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein 9',
  'Mishneh Torah, Admission into the Sanctuary 1',
  'Mishneh Torah, Admission into the Sanctuary 2',
  'Mishneh Torah, Admission into the Sanctuary 3',
  'Mishneh Torah, Admission into the Sanctuary 4',
  'Mishneh Torah, Admission into the Sanctuary 5',
  'Mishneh Torah, Admission into the Sanctuary 6',
  'Mishneh Torah, Admission into the Sanctuary 7',
  'Mishneh Torah, Admission into the Sanctuary 8',
  'Mishneh Torah, Things Forbidden on the Altar 1',
  'Mishneh Torah, Things Forbidden on the Altar 2',
  'Mishneh Torah, Things Forbidden on the Altar 3',
  'Mishneh Torah, Things Forbidden on the Altar 4',
  'Mishneh Torah, Things Forbidden on the Altar 5',
  'Mishneh Torah, Things Forbidden on the Altar 6',
  'Mishneh Torah, Things Forbidden on the Altar 7',
  'Mishneh Torah, Sacrificial Procedure 1',
  'Mishneh Torah, Sacrificial Procedure 2',
  'Mishneh Torah, Sacrificial Procedure 3',
  'Mishneh Torah, Sacrificial Procedure 4',
  'Mishneh Torah, Sacrificial Procedure 5',
  'Mishneh Torah, Sacrificial Procedure 6',
  'Mishneh Torah, Sacrificial Procedure 7',
  'Mishneh Torah, Sacrificial Procedure 8',
  'Mishneh Torah, Sacrificial Procedure 9',
  'Mishneh Torah, Sacrificial Procedure 10',
  'Mishneh Torah, Sacrificial Procedure 11',
  'Mishneh Torah, Sacrificial Procedure 12',
  'Mishneh Torah, Sacrificial Procedure 13',
  'Mishneh Torah, Sacrificial Procedure 14',
  'Mishneh Torah, Sacrificial Procedure 15',
  'Mishneh Torah, Sacrificial Procedure 16',
  'Mishneh Torah, Sacrificial Procedure 17',
  'Mishneh Torah, Sacrificial Procedure 18',
  'Mishneh Torah, Sacrificial Procedure 19',
  'Mishneh Torah, Daily Offerings and Additional Offerings 1',
  'Mishneh Torah, Daily Offerings and Additional Offerings 2',
  'Mishneh Torah, Daily Offerings and Additional Offerings 3',
  'Mishneh Torah, Daily Offerings and Additional Offerings 4',
  'Mishneh Torah, Daily Offerings and Additional Offerings 5',
  'Mishneh Torah, Daily Offerings and Additional Offerings 6',
  'Mishneh Torah, Daily Offerings and Additional Offerings 7',
  'Mishneh Torah, Daily Offerings and Additional Offerings 8',
  'Mishneh Torah, Daily Offerings and Additional Offerings 9',
  'Mishneh Torah, Sacrifices Rendered Unfit 1',
  'Mishneh Torah, Sacrifices Rendered Unfit 2',
  'Mishneh Torah, Sacrifices Rendered Unfit 3',
  'Mishneh Torah, Sacrifices Rendered Unfit 4',
  'Mishneh Torah, Sacrifices Rendered Unfit 5',
  'Mishneh Torah, Sacrifices Rendered Unfit 6',
  'Mishneh Torah, Sacrifices Rendered Unfit 7',
  'Mishneh Torah, Sacrifices Rendered Unfit 8',
  'Mishneh Torah, Sacrifices Rendered Unfit 9',
  'Mishneh Torah, Sacrifices Rendered Unfit 10',
  'Mishneh Torah, Sacrifices Rendered Unfit 11',
  'Mishneh Torah, Sacrifices Rendered Unfit 12',
  'Mishneh Torah, Sacrifices Rendered Unfit 13',
  'Mishneh Torah, Sacrifices Rendered Unfit 14',
  'Mishneh Torah, Sacrifices Rendered Unfit 15',
  'Mishneh Torah, Sacrifices Rendered Unfit 16',
  'Mishneh Torah, Sacrifices Rendered Unfit 17',
  'Mishneh Torah, Sacrifices Rendered Unfit 18',
  'Mishneh Torah, Sacrifices Rendered Unfit 19',
  'Mishneh Torah, Service on the Day of Atonement 1',
  'Mishneh Torah, Service on the Day of Atonement 2',
  'Mishneh Torah, Service on the Day of Atonement 3',
  'Mishneh Torah, Service on the Day of Atonement 4',
  'Mishneh Torah, Trespass 1',
  'Mishneh Torah, Trespass 2',
  'Mishneh Torah, Trespass 3',
  'Mishneh Torah, Trespass 4',
  'Mishneh Torah, Trespass 5',
  'Mishneh Torah, Trespass 6',
  'Mishneh Torah, Trespass 7',
  'Mishneh Torah, Trespass 8',
  'Mishneh Torah, Paschal Offering 1',
  'Mishneh Torah, Paschal Offering 2',
  'Mishneh Torah, Paschal Offering 3',
  'Mishneh Torah, Paschal Offering 4',
  'Mishneh Torah, Paschal Offering 5',
  'Mishneh Torah, Paschal Offering 6',
  'Mishneh Torah, Paschal Offering 7',
  'Mishneh Torah, Paschal Offering 8',
  'Mishneh Torah, Paschal Offering 9',
  'Mishneh Torah, Festival Offering 1',
  'Mishneh Torah, Festival Offering 2',
  'Mishneh Torah, Firstlings 1',
  'Mishneh Torah, Firstlings 2',
  'Mishneh Torah, Firstlings 3',
  'Mishneh Torah, Firstlings 4',
  'Mishneh Torah, Firstlings 5',
  'Mishneh Torah, Firstlings 6',
  'Mishneh Torah, Firstlings 7',
  'Mishneh Torah, Firstlings 8',
  'Mishneh Torah, Offerings for Unintentional Transgressions 1',
  'Mishneh Torah, Offerings for Unintentional Transgressions 2',
  'Mishneh Torah, Offerings for Unintentional Transgressions 3',
  'Mishneh Torah, Offerings for Unintentional Transgressions 4',
  'Mishneh Torah, Offerings for Unintentional Transgressions 5',
  'Mishneh Torah, Offerings for Unintentional Transgressions 6',
  'Mishneh Torah, Offerings for Unintentional Transgressions 7',
  'Mishneh Torah, Offerings for Unintentional Transgressions 8',
  'Mishneh Torah, Offerings for Unintentional Transgressions 9',
  'Mishneh Torah, Offerings for Unintentional Transgressions 10',
  'Mishneh Torah, Offerings for Unintentional Transgressions 11',
  'Mishneh Torah, Offerings for Unintentional Transgressions 12',
  'Mishneh Torah, Offerings for Unintentional Transgressions 13',
  'Mishneh Torah, Offerings for Unintentional Transgressions 14',
  'Mishneh Torah, Offerings for Unintentional Transgressions 15',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 1',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 2',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 3',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 4',
  'Mishneh Torah, Offerings for Those with Incomplete Atonement 5',
  'Mishneh Torah, Substitution 1',
  'Mishneh Torah, Substitution 2',
  'Mishneh Torah, Substitution 3',
  'Mishneh Torah, Substitution 4',
  'Mishneh Torah, Defilement by a Corpse 1',
  'Mishneh Torah, Defilement by a Corpse 2',
  'Mishneh Torah, Defilement by a Corpse 3',
  'Mishneh Torah, Defilement by a Corpse 4',
  'Mishneh Torah, Defilement by a Corpse 5',
  'Mishneh Torah, Defilement by a Corpse 6',
  'Mishneh Torah, Defilement by a Corpse 7',
  'Mishneh Torah, Defilement by a Corpse 8',
  'Mishneh Torah, Defilement by a Corpse 9',
  'Mishneh Torah, Defilement by a Corpse 10',
  'Mishneh Torah, Defilement by a Corpse 11',
  'Mishneh Torah, Defilement by a Corpse 12',
  'Mishneh Torah, Defilement by a Corpse 13',
  'Mishneh Torah, Defilement by a Corpse 14',
  'Mishneh Torah, Defilement by a Corpse 15',
  'Mishneh Torah, Defilement by a Corpse 16',
  'Mishneh Torah, Defilement by a Corpse 17',
  'Mishneh Torah, Defilement by a Corpse 18',
  'Mishneh Torah, Defilement by a Corpse 19',
  'Mishneh Torah, Defilement by a Corpse 20',
  'Mishneh Torah, Defilement by a Corpse 21',
  'Mishneh Torah, Defilement by a Corpse 22',
  'Mishneh Torah, Defilement by a Corpse 23',
  'Mishneh Torah, Defilement by a Corpse 24',
  'Mishneh Torah, Red Heifer 1',
  'Mishneh Torah, Red Heifer 2',
  'Mishneh Torah, Red Heifer 3',
  'Mishneh Torah, Red Heifer 4',
  'Mishneh Torah, Red Heifer 5',
  'Mishneh Torah, Red Heifer 6',
  'Mishneh Torah, Red Heifer 7',
  'Mishneh Torah, Red Heifer 8',
  'Mishneh Torah, Red Heifer 9',
  'Mishneh Torah, Red Heifer 10',
  'Mishneh Torah, Red Heifer 11',
  'Mishneh Torah, Red Heifer 12',
  'Mishneh Torah, Red Heifer 13',
  'Mishneh Torah, Red Heifer 14',
  'Mishneh Torah, Defilement by Leprosy 1',
  'Mishneh Torah, Defilement by Leprosy 2',
  'Mishneh Torah, Defilement by Leprosy 3',
  'Mishneh Torah, Defilement by Leprosy 4',
  'Mishneh Torah, Defilement by Leprosy 5',
  'Mishneh Torah, Defilement by Leprosy 6',
  'Mishneh Torah, Defilement by Leprosy 7',
  'Mishneh Torah, Defilement by Leprosy 8',
  'Mishneh Torah, Defilement by Leprosy 9',
  'Mishneh Torah, Defilement by Leprosy 10',
  'Mishneh Torah, Defilement by Leprosy 11',
  'Mishneh Torah, Defilement by Leprosy 12',
  'Mishneh Torah, Defilement by Leprosy 13',
  'Mishneh Torah, Defilement by Leprosy 14',
  'Mishneh Torah, Defilement by Leprosy 15',
  'Mishneh Torah, Defilement by Leprosy 16',
  'Mishneh Torah, Those Who Defile Bed or Seat 1',
  'Mishneh Torah, Those Who Defile Bed or Seat 2',
  'Mishneh Torah, Those Who Defile Bed or Seat 3',
  'Mishneh Torah, Those Who Defile Bed or Seat 4',
  'Mishneh Torah, Those Who Defile Bed or Seat 5',
  'Mishneh Torah, Those Who Defile Bed or Seat 6',
  'Mishneh Torah, Those Who Defile Bed or Seat 7',
  'Mishneh Torah, Those Who Defile Bed or Seat 8',
  'Mishneh Torah, Those Who Defile Bed or Seat 9',
  'Mishneh Torah, Those Who Defile Bed or Seat 10',
  'Mishneh Torah, Those Who Defile Bed or Seat 11',
  'Mishneh Torah, Those Who Defile Bed or Seat 12',
  'Mishneh Torah, Those Who Defile Bed or Seat 13',
  'Mishneh Torah, Other Sources of Defilement 1',
  'Mishneh Torah, Other Sources of Defilement 2',
  'Mishneh Torah, Other Sources of Defilement 3',
  'Mishneh Torah, Other Sources of Defilement 4',
  'Mishneh Torah, Other Sources of Defilement 5',
  'Mishneh Torah, Other Sources of Defilement 6',
  'Mishneh Torah, Other Sources of Defilement 7',
  'Mishneh Torah, Other Sources of Defilement 8',
  'Mishneh Torah, Other Sources of Defilement 9',
  'Mishneh Torah, Other Sources of Defilement 10',
  'Mishneh Torah, Other Sources of Defilement 11',
  'Mishneh Torah, Other Sources of Defilement 12',
  'Mishneh Torah, Other Sources of Defilement 13',
  'Mishneh Torah, Other Sources of Defilement 14',
  'Mishneh Torah, Other Sources of Defilement 15',
  'Mishneh Torah, Other Sources of Defilement 16',
  'Mishneh Torah, Other Sources of Defilement 17',
  'Mishneh Torah, Other Sources of Defilement 18',
  'Mishneh Torah, Other Sources of Defilement 19',
  'Mishneh Torah, Other Sources of Defilement 20',
  'Mishneh Torah, Defilement of Foods 1',
  'Mishneh Torah, Defilement of Foods 2',
  'Mishneh Torah, Defilement of Foods 3',
  'Mishneh Torah, Defilement of Foods 4',
  'Mishneh Torah, Defilement of Foods 5',
  'Mishneh Torah, Defilement of Foods 6',
  'Mishneh Torah, Defilement of Foods 7',
  'Mishneh Torah, Defilement of Foods 8',
  'Mishneh Torah, Defilement of Foods 9',
  'Mishneh Torah, Defilement of Foods 10',
  'Mishneh Torah, Defilement of Foods 11',
  'Mishneh Torah, Defilement of Foods 12',
  'Mishneh Torah, Defilement of Foods 13',
  'Mishneh Torah, Defilement of Foods 14',
  'Mishneh Torah, Defilement of Foods 15',
  'Mishneh Torah, Defilement of Foods 16',
  'Mishneh Torah, Vessels 1',
  'Mishneh Torah, Vessels 2',
  'Mishneh Torah, Vessels 3',
  'Mishneh Torah, Vessels 4',
  'Mishneh Torah, Vessels 5',
  'Mishneh Torah, Vessels 6',
  'Mishneh Torah, Vessels 7',
  'Mishneh Torah, Vessels 8',
  'Mishneh Torah, Vessels 9',
  'Mishneh Torah, Vessels 10',
  'Mishneh Torah, Vessels 11',
  'Mishneh Torah, Vessels 12',
  'Mishneh Torah, Vessels 13',
  'Mishneh Torah, Vessels 14',
  'Mishneh Torah, Vessels 15',
  'Mishneh Torah, Vessels 16',
  'Mishneh Torah, Vessels 17',
  'Mishneh Torah, Vessels 18',
  'Mishneh Torah, Vessels 19',
  'Mishneh Torah, Vessels 20',
  'Mishneh Torah, Vessels 21',
  'Mishneh Torah, Vessels 22',
  'Mishneh Torah, Vessels 23',
  'Mishneh Torah, Vessels 24',
  'Mishneh Torah, Vessels 25',
  'Mishneh Torah, Vessels 26',
  'Mishneh Torah, Vessels 27',
  'Mishneh Torah, Immersion Pools 1',
  'Mishneh Torah, Immersion Pools 2',
  'Mishneh Torah, Immersion Pools 3',
  'Mishneh Torah, Immersion Pools 4',
  'Mishneh Torah, Immersion Pools 5',
  'Mishneh Torah, Immersion Pools 6',
  'Mishneh Torah, Immersion Pools 7',
  'Mishneh Torah, Immersion Pools 8',
  'Mishneh Torah, Immersion Pools 9',
  'Mishneh Torah, Immersion Pools 10',
  'Mishneh Torah, Immersion Pools 11',
  'Mishneh Torah, Damages to Property 1',
  'Mishneh Torah, Damages to Property 2',
  'Mishneh Torah, Damages to Property 3',
  'Mishneh Torah, Damages to Property 4',
  'Mishneh Torah, Damages to Property 5',
  'Mishneh Torah, Damages to Property 6',
  'Mishneh Torah, Damages to Property 7',
  'Mishneh Torah, Damages to Property 8',
  'Mishneh Torah, Damages to Property 9',
  'Mishneh Torah, Damages to Property 10',
  'Mishneh Torah, Damages to Property 11',
  'Mishneh Torah, Damages to Property 12',
  'Mishneh Torah, Damages to Property 13',
  'Mishneh Torah, Damages to Property 14',
  'Mishneh Torah, Theft 1',
  'Mishneh Torah, Theft 2',
  'Mishneh Torah, Theft 3',
  'Mishneh Torah, Theft 4',
  'Mishneh Torah, Theft 5',
  'Mishneh Torah, Theft 6',
  'Mishneh Torah, Theft 7',
  'Mishneh Torah, Theft 8',
  'Mishneh Torah, Theft 9',
  'Mishneh Torah, Robbery and Lost Property 1',
  'Mishneh Torah, Robbery and Lost Property 2',
  'Mishneh Torah, Robbery and Lost Property 3',
  'Mishneh Torah, Robbery and Lost Property 4',
  'Mishneh Torah, Robbery and Lost Property 5',
  'Mishneh Torah, Robbery and Lost Property 6',
  'Mishneh Torah, Robbery and Lost Property 7',
  'Mishneh Torah, Robbery and Lost Property 8',
  'Mishneh Torah, Robbery and Lost Property 9',
  'Mishneh Torah, Robbery and Lost Property 10',
  'Mishneh Torah, Robbery and Lost Property 11',
  'Mishneh Torah, Robbery and Lost Property 12',
  'Mishneh Torah, Robbery and Lost Property 13',
  'Mishneh Torah, Robbery and Lost Property 14',
  'Mishneh Torah, Robbery and Lost Property 15',
  'Mishneh Torah, Robbery and Lost Property 16',
  'Mishneh Torah, Robbery and Lost Property 17',
  'Mishneh Torah, Robbery and Lost Property 18',
  'Mishneh Torah, One Who Injures a Person or Property 1',
  'Mishneh Torah, One Who Injures a Person or Property 2',
  'Mishneh Torah, One Who Injures a Person or Property 3',
  'Mishneh Torah, One Who Injures a Person or Property 4',
  'Mishneh Torah, One Who Injures a Person or Property 5',
  'Mishneh Torah, One Who Injures a Person or Property 6',
  'Mishneh Torah, One Who Injures a Person or Property 7',
  'Mishneh Torah, Murderer and the Preservation of Life 1',
  'Mishneh Torah, Murderer and the Preservation of Life 2',
  'Mishneh Torah, Murderer and the Preservation of Life 3',
  'Mishneh Torah, Murderer and the Preservation of Life 4',
  'Mishneh Torah, Murderer and the Preservation of Life 5',
  'Mishneh Torah, Murderer and the Preservation of Life 6',
  'Mishneh Torah, Murderer and the Preservation of Life 7',
  'Mishneh Torah, Murderer and the Preservation of Life 8',
  'Mishneh Torah, Murderer and the Preservation of Life 9',
  'Mishneh Torah, Murderer and the Preservation of Life 10',
  'Mishneh Torah, Murderer and the Preservation of Life 11',
  'Mishneh Torah, Murderer and the Preservation of Life 12',
  'Mishneh Torah, Murderer and the Preservation of Life 13',
  'Mishneh Torah, Sales 1',
  'Mishneh Torah, Sales 2',
  'Mishneh Torah, Sales 3',
  'Mishneh Torah, Sales 4',
  'Mishneh Torah, Sales 5',
  'Mishneh Torah, Sales 6',
  'Mishneh Torah, Sales 7',
  'Mishneh Torah, Sales 8',
  'Mishneh Torah, Sales 9',
  'Mishneh Torah, Sales 10',
  'Mishneh Torah, Sales 11',
  'Mishneh Torah, Sales 12',
  'Mishneh Torah, Sales 13',
  'Mishneh Torah, Sales 14',
  'Mishneh Torah, Sales 15',
  'Mishneh Torah, Sales 16',
  'Mishneh Torah, Sales 17',
  'Mishneh Torah, Sales 18',
  'Mishneh Torah, Sales 19',
  'Mishneh Torah, Sales 20',
  'Mishneh Torah, Sales 21',
  'Mishneh Torah, Sales 22',
  'Mishneh Torah, Sales 23',
  'Mishneh Torah, Sales 24',
  'Mishneh Torah, Sales 25',
  'Mishneh Torah, Sales 26',
  'Mishneh Torah, Sales 27',
  'Mishneh Torah, Sales 28',
  'Mishneh Torah, Sales 29',
  'Mishneh Torah, Sales 30',
  'Mishneh Torah, Ownerless Property and Gifts 1',
  'Mishneh Torah, Ownerless Property and Gifts 2',
  'Mishneh Torah, Ownerless Property and Gifts 3',
  'Mishneh Torah, Ownerless Property and Gifts 4',
  'Mishneh Torah, Ownerless Property and Gifts 5',
  'Mishneh Torah, Ownerless Property and Gifts 6',
  'Mishneh Torah, Ownerless Property and Gifts 7',
  'Mishneh Torah, Ownerless Property and Gifts 8',
  'Mishneh Torah, Ownerless Property and Gifts 9',
  'Mishneh Torah, Ownerless Property and Gifts 10',
  'Mishneh Torah, Ownerless Property and Gifts 11',
  'Mishneh Torah, Ownerless Property and Gifts 12',
  'Mishneh Torah, Neighbors 1',
  'Mishneh Torah, Neighbors 2',
  'Mishneh Torah, Neighbors 3',
  'Mishneh Torah, Neighbors 4',
  'Mishneh Torah, Neighbors 5',
  'Mishneh Torah, Neighbors 6',
  'Mishneh Torah, Neighbors 7',
  'Mishneh Torah, Neighbors 8',
  'Mishneh Torah, Neighbors 9',
  'Mishneh Torah, Neighbors 10',
  'Mishneh Torah, Neighbors 11',
  'Mishneh Torah, Neighbors 12',
  'Mishneh Torah, Neighbors 13',
  'Mishneh Torah, Agents and Partners 1',
  'Mishneh Torah, Agents and Partners 2',
  'Mishneh Torah, Agents and Partners 3',
  'Mishneh Torah, Agents and Partners 4',
  'Mishneh Torah, Agents and Partners 5',
  'Mishneh Torah, Agents and Partners 6',
  'Mishneh Torah, Agents and Partners 7',
  'Mishneh Torah, Agents and Partners 8',
  'Mishneh Torah, Agents and Partners 9',
  'Mishneh Torah, Agents and Partners 10',
  'Mishneh Torah, Slaves 1',
  'Mishneh Torah, Slaves 2',
  'Mishneh Torah, Slaves 3',
  'Mishneh Torah, Slaves 4',
  'Mishneh Torah, Slaves 5',
  'Mishneh Torah, Slaves 6',
  'Mishneh Torah, Slaves 7',
  'Mishneh Torah, Slaves 8',
  'Mishneh Torah, Slaves 9',
  'Mishneh Torah, Hiring 1',
  'Mishneh Torah, Hiring 2',
  'Mishneh Torah, Hiring 3',
  'Mishneh Torah, Hiring 4',
  'Mishneh Torah, Hiring 5',
  'Mishneh Torah, Hiring 6',
  'Mishneh Torah, Hiring 7',
  'Mishneh Torah, Hiring 8',
  'Mishneh Torah, Hiring 9',
  'Mishneh Torah, Hiring 10',
  'Mishneh Torah, Hiring 11',
  'Mishneh Torah, Hiring 12',
  'Mishneh Torah, Hiring 13',
  'Mishneh Torah, Borrowing and Deposit 1',
  'Mishneh Torah, Borrowing and Deposit 2',
  'Mishneh Torah, Borrowing and Deposit 3',
  'Mishneh Torah, Borrowing and Deposit 4',
  'Mishneh Torah, Borrowing and Deposit 5',
  'Mishneh Torah, Borrowing and Deposit 6',
  'Mishneh Torah, Borrowing and Deposit 7',
  'Mishneh Torah, Borrowing and Deposit 8',
  'Mishneh Torah, Creditor and Debtor 1',
  'Mishneh Torah, Creditor and Debtor 2',
  'Mishneh Torah, Creditor and Debtor 3',
  'Mishneh Torah, Creditor and Debtor 4',
  'Mishneh Torah, Creditor and Debtor 5',
  'Mishneh Torah, Creditor and Debtor 6',
  'Mishneh Torah, Creditor and Debtor 7',
  'Mishneh Torah, Creditor and Debtor 8',
  'Mishneh Torah, Creditor and Debtor 9',
  'Mishneh Torah, Creditor and Debtor 10',
  'Mishneh Torah, Creditor and Debtor 11',
  'Mishneh Torah, Creditor and Debtor 12',
  'Mishneh Torah, Creditor and Debtor 13',
  'Mishneh Torah, Creditor and Debtor 14',
  'Mishneh Torah, Creditor and Debtor 15',
  'Mishneh Torah, Creditor and Debtor 16',
  'Mishneh Torah, Creditor and Debtor 17',
  'Mishneh Torah, Creditor and Debtor 18',
  'Mishneh Torah, Creditor and Debtor 19',
  'Mishneh Torah, Creditor and Debtor 20',
  'Mishneh Torah, Creditor and Debtor 21',
  'Mishneh Torah, Creditor and Debtor 22',
  'Mishneh Torah, Creditor and Debtor 23',
  'Mishneh Torah, Creditor and Debtor 24',
  'Mishneh Torah, Creditor and Debtor 25',
  'Mishneh Torah, Creditor and Debtor 26',
  'Mishneh Torah, Creditor and Debtor 27',
  'Mishneh Torah, Plaintiff and Defendant 1',
  'Mishneh Torah, Plaintiff and Defendant 2',
  'Mishneh Torah, Plaintiff and Defendant 3',
  'Mishneh Torah, Plaintiff and Defendant 4',
  'Mishneh Torah, Plaintiff and Defendant 5',
  'Mishneh Torah, Plaintiff and Defendant 6',
  'Mishneh Torah, Plaintiff and Defendant 7',
  'Mishneh Torah, Plaintiff and Defendant 8',
  'Mishneh Torah, Plaintiff and Defendant 9',
  'Mishneh Torah, Plaintiff and Defendant 10',
  'Mishneh Torah, Plaintiff and Defendant 11',
  'Mishneh Torah, Plaintiff and Defendant 12',
  'Mishneh Torah, Plaintiff and Defendant 13',
  'Mishneh Torah, Plaintiff and Defendant 14',
  'Mishneh Torah, Plaintiff and Defendant 15',
  'Mishneh Torah, Plaintiff and Defendant 16',
  'Mishneh Torah, Inheritances 1',
  'Mishneh Torah, Inheritances 2',
  'Mishneh Torah, Inheritances 3',
  'Mishneh Torah, Inheritances 4',
  'Mishneh Torah, Inheritances 5',
  'Mishneh Torah, Inheritances 6',
  'Mishneh Torah, Inheritances 7',
  'Mishneh Torah, Inheritances 8',
  'Mishneh Torah, Inheritances 9',
  'Mishneh Torah, Inheritances 10',
  'Mishneh Torah, Inheritances 11',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 1',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 2',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 3',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 4',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 5',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 6',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 7',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 8',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 9',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 10',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 11',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 12',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 13',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 14',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 15',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 16',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 17',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 18',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 19',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 20',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 21',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 22',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 23',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 24',
  'Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction 25',
  'Mishneh Torah, Testimony 1',
  'Mishneh Torah, Testimony 2',
  'Mishneh Torah, Testimony 3',
  'Mishneh Torah, Testimony 4',
  'Mishneh Torah, Testimony 5',
  'Mishneh Torah, Testimony 6',
  'Mishneh Torah, Testimony 7',
  'Mishneh Torah, Testimony 8',
  'Mishneh Torah, Testimony 9',
  'Mishneh Torah, Testimony 10',
  'Mishneh Torah, Testimony 11',
  'Mishneh Torah, Testimony 12',
  'Mishneh Torah, Testimony 13',
  'Mishneh Torah, Testimony 14',
  'Mishneh Torah, Testimony 15',
  'Mishneh Torah, Testimony 16',
  'Mishneh Torah, Testimony 17',
  'Mishneh Torah, Testimony 18',
  'Mishneh Torah, Testimony 19',
  'Mishneh Torah, Testimony 20',
  'Mishneh Torah, Testimony 21',
  'Mishneh Torah, Testimony 22',
  'Mishneh Torah, Rebels 1',
  'Mishneh Torah, Rebels 2',
  'Mishneh Torah, Rebels 3',
  'Mishneh Torah, Rebels 4',
  'Mishneh Torah, Rebels 5',
  'Mishneh Torah, Rebels 6',
  'Mishneh Torah, Rebels 7',
  'Mishneh Torah, Mourning 1',
  'Mishneh Torah, Mourning 2',
  'Mishneh Torah, Mourning 3',
  'Mishneh Torah, Mourning 4',
  'Mishneh Torah, Mourning 5',
  'Mishneh Torah, Mourning 6',
  'Mishneh Torah, Mourning 7',
  'Mishneh Torah, Mourning 8',
  'Mishneh Torah, Mourning 9',
  'Mishneh Torah, Mourning 10',
  'Mishneh Torah, Mourning 11',
  'Mishneh Torah, Mourning 12',
  'Mishneh Torah, Mourning 13',
  'Mishneh Torah, Mourning 14',
  'Mishneh Torah, Kings and Wars 1',
  'Mishneh Torah, Kings and Wars 2',
  'Mishneh Torah, Kings and Wars 3',
  'Mishneh Torah, Kings and Wars 4',
  'Mishneh Torah, Kings and Wars 5',
  'Mishneh Torah, Kings and Wars 6',
  'Mishneh Torah, Kings and Wars 7',
  'Mishneh Torah, Kings and Wars 8',
  'Mishneh Torah, Kings and Wars 9',
  'Mishneh Torah, Kings and Wars 10',
  'Mishneh Torah, Kings and Wars 11',
  'Mishneh Torah, Kings and Wars 12',
];
