import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:learning_tracker/core/domain/value_objects/profile_mode.dart';
import 'package:learning_tracker/features/learning/presentation/providers/completion_writer_providers.dart';
import 'package:learning_tracker/features/progress/domain/models/chart_data.dart';
import 'package:learning_tracker/features/progress/domain/services/chart_data_service.dart';
import 'package:learning_tracker/features/progress/presentation/providers/chart_providers.dart';
import 'package:learning_tracker/features/progress/presentation/providers/progress_lens_refresh_tick_provider.dart';

part 'recent_activity_providers.freezed.dart';

/// Provider wiring for the Recent Activity screen (engagement-tier lens).
///
/// The screen renders four data feeds, each live-only:
///  1. Limudim & Chazaros stacked bar chart
///     ([ChartDataService.getDailyLimudimAndChazaros]).
///  2. Cumulative line chart, live-only
///     ([ChartDataService.getCumulativeProgressLive]).
///  3. Points-over-time bar (child mode only)
///     ([ChartDataService.getDailyPoints], already live-only by tier policy).
///  4. Streak weekly dots / calendar
///     ([ChartDataService.getStreakCalendarLive]).
///
/// All four feeds share the same window. We pin the window into a single
/// [RecentActivityWindow] value (used as a [FutureProvider.family] key) so
/// each provider naturally memoizes per (range, curriculum, dates) without
/// the screen having to maintain ad-hoc caches in `setState`.
///
/// Provider families are `autoDispose` so off-screen disposal frees the
/// service work; rebuilding with the same key replays the cached future.

/// Identifier for a Recent Activity data window.
///
/// Equality is structural (generated by `@freezed`) so [FutureProvider.family]
/// memoizes per identical (range, curriculum, start, end) — re-renders with
/// the same window get the cached future, switching range or curriculum gets
/// a fresh fetch. Generated equality also means a field added to this type
/// later is automatically included in `==`/`hashCode` — a hand-written
/// override could silently forget it and under-compare, causing stale
/// `FutureProvider.family` cache hits (AUD-progress-15).
@freezed
abstract class RecentActivityWindow with _$RecentActivityWindow {
  const factory RecentActivityWindow({
    required DateTime startDate,
    required DateTime endDate,
    String? curriculumId,
  }) = _RecentActivityWindow;
}

/// Live limudim+chazaros stacked-bar data for the given window.
final recentActivityLimudimChazarosProvider = FutureProvider.autoDispose
    .family<List<DailyLimudChazaraData>, RecentActivityWindow>((
      ref,
      window,
    ) async {
      ref.watch(progressLensRefreshTickProvider);
      // RA-03: react to live completions immediately (not only on pull-to-refresh).
      ref.watch<int>(completionCommittedProvider);
      final service = ref.watch(chartDataServiceProvider);
      return service.getDailyLimudimAndChazaros(
        startDate: window.startDate,
        endDate: window.endDate,
        curriculumId: window.curriculumId,
      );
    });

/// Live cumulative-line data for the given window.
final recentActivityCumulativeProvider = FutureProvider.autoDispose
    .family<List<CumulativeProgressPoint>, RecentActivityWindow>((
      ref,
      window,
    ) async {
      ref.watch(progressLensRefreshTickProvider);
      // RA-03: react to live completions immediately (not only on pull-to-refresh).
      ref.watch<int>(completionCommittedProvider);
      final service = ref.watch(chartDataServiceProvider);
      return service.getCumulativeProgressLive(
        startDate: window.startDate,
        endDate: window.endDate,
        curriculumId: window.curriculumId,
      );
    });

/// Live streak calendar for the given window. The set contains every local
/// date in [window.startDate]..[window.endDate] that has at least one live
/// completion — scoped to [window.curriculumId] when the user picks a
/// specific curriculum chip (F11 — W7-D fix wave: previously the provider
/// key encoded curriculum but the call ignored it, so the calendar dots
/// stayed unchanged when the chip changed).
final recentActivityStreakDatesProvider = FutureProvider.autoDispose
    .family<Set<DateTime>, RecentActivityWindow>((ref, window) async {
      ref.watch(progressLensRefreshTickProvider);
      // RA-03: react to live completions immediately (not only on pull-to-refresh).
      ref.watch<int>(completionCommittedProvider);
      final service = ref.watch(chartDataServiceProvider);
      return service.getStreakCalendarLive(
        startDate: window.startDate,
        endDate: window.endDate,
        curriculumId: window.curriculumId,
      );
    });

/// Live daily-points data for the given window. The underlying service
/// returns `null` for adult mode; we forward that so the screen can
/// conditionally hide the section.
final recentActivityPointsProvider = FutureProvider.autoDispose
    .family<List<DailyPointsData>?, RecentActivityWindow>((ref, window) async {
      ref.watch(progressLensRefreshTickProvider);
      // RA-03: react to live completions immediately (not only on pull-to-refresh).
      ref.watch<int>(completionCommittedProvider);
      final service = ref.watch(chartDataServiceProvider);
      return service.getDailyPoints(
        startDate: window.startDate,
        endDate: window.endDate,
        userMode: ProfileMode.child,
        curriculumId: window.curriculumId,
      );
    });
