import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:learning_tracker/core/enums/curriculum_id.dart';

part 'daily_task.freezed.dart';

/// Priority ranking for daily tasks.
///
/// Ordering:
///   overdueProgram > todayProgram > overdueChazara >
///   overdueNewLearning > scheduledChazara > newLearning
enum DailyTaskPriority {
  /// Program item that is past due (missed a calendar day).
  overdueProgram,

  /// Program item scheduled for today.
  todayProgram,

  /// Chazara that is past its scheduled review date.
  overdueChazara,

  /// New content that was shown in a prior-day snapshot but never completed.
  ///
  /// Distinguished from [overdueChazara]: the item has no completion history
  /// at all — it was scheduled for a previous day but has never been studied.
  /// The UI should present this as "pick up where you left off" rather than
  /// "review something you already know".
  ///
  /// Added by DNI-346 to fix the bug where brand-new never-completed items
  /// in the snapshot path were incorrectly labelled as [overdueChazara].
  overdueNewLearning,

  /// Chazara that is due today.
  scheduledChazara,

  /// New content that hasn't been learned yet.
  newLearning,
}

/// A single task recommendation generated by the scheduler.
@freezed
abstract class DailyTask with _$DailyTask {
  const factory DailyTask({
    required CurriculumId curriculumId,
    required String contentItemSefariaRef,
    required int stageOrder,
    required DailyTaskPriority priority,
    required bool isOverdue,
    required String reason,
    required String stageName,

    /// Display label for the track (e.g., "Daf Yomi", "Mishnayos - School").
    required String trackLabel,

    /// Estimated effort in minutes. Defaults based on priority:
    /// newLearning = 5 min, chazara = 3 min.
    @Default(3) int estimatedEffortMinutes,

    /// Seed-sourced day-level unit label in Hebrew (e.g. "חולין דף כ״ה" for a
    /// Daf-Yomi day, "כלים 5:7-8" for a mishnayos range).
    ///
    /// Populated at generation time for program tasks from the calendar
    /// entry's `todayRefHe`. This is the *collapsed, type-aware* name for the
    /// whole day's unit — a single daf rather than one amud breadcrumb. The
    /// dashboard track card prefers this over re-deriving an expanded amud
    /// label from [contentItemSefariaRef] at render time, which makes the
    /// displayed unit reliable. Null for self-paced tasks and any program
    /// entry whose seed lacks a Hebrew label.
    String? unitDisplayHe,

    /// Seed-sourced day-level unit label in English (e.g. "Chullin 25",
    /// "Kelim 5:7-8"). English counterpart of [unitDisplayHe]; null in the
    /// same cases.
    String? unitDisplayEn,
  }) = _DailyTask;
}
