import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:learning_tracker/core/enums/curriculum_id.dart';

part 'daily_task.freezed.dart';

/// Priority ranking for daily tasks.
///
/// Ordering: overdueProgram > todayProgram > overdueChazara > scheduledChazara > newLearning
enum DailyTaskPriority {
  /// Program item that is past due (missed a calendar day).
  overdueProgram,

  /// Program item scheduled for today.
  todayProgram,

  /// Chazara that is past its scheduled review date.
  overdueChazara,

  /// Chazara that is due today.
  scheduledChazara,

  /// New content that hasn't been learned yet.
  newLearning,
}

/// A single task recommendation generated by the scheduler.
@freezed
abstract class DailyTask with _$DailyTask {
  const factory DailyTask({
    required CurriculumId curriculumId,
    required String contentItemSefariaRef,
    required int stageOrder,
    required int stageDefinitionId,
    required DailyTaskPriority priority,
    required bool isOverdue,
    required String reason,
    required String stageName,

    /// The track that produced this task.
    required int trackId,

    /// Display label for the track (e.g., "Daf Yomi", "Mishnayos - School").
    required String trackLabel,

    /// Estimated effort in minutes. Defaults based on priority:
    /// newLearning = 5 min, chazara = 3 min.
    @Default(3) int estimatedEffortMinutes,
  }) = _DailyTask;
}
