import 'package:freezed_annotation/freezed_annotation.dart';

part 'daily_task.freezed.dart';

/// Priority ranking for daily tasks.
///
/// Ordering: overdueChazara > scheduledChazara > newLearning
enum DailyTaskPriority {
  /// Chazara that is past its scheduled review date.
  overdueChazara,

  /// Chazara that is due today.
  scheduledChazara,

  /// New content that hasn't been learned yet.
  newLearning,
}

/// A single task recommendation generated by the scheduler.
@freezed
abstract class DailyTask with _$DailyTask {
  const factory DailyTask({
    required String contentItemSefariaRef,
    required int stageOrder,
    required DailyTaskPriority priority,
    required String reason,
  }) = _DailyTask;
}
